(function(){var l,q;function aa(a){return(a=Number(a))?0<a?1:-1:a};var ba=Object.prototype.hasOwnProperty;function ca(a,b){if(null==a)throw new TypeError("Cannot convert undefined or null to object");for(var c=Object(a),d=1;d<arguments.length;d++){var e=arguments[d];if(null!=e)for(var f in e)ba.call(e,f)&&(c[f]=e[f])}return c};function da(a){return Object.keys(a).map(function(b){return a[b]})};(function(a){a.Math.sign||a.Object.defineProperty(a.Math,"sign",{enumerable:!1,configurable:!0,writable:!0,value:aa})})(self);(function(a){a.Object.assign||a.Object.defineProperty(a.Object,"assign",{enumerable:!1,configurable:!0,writable:!0,value:ca})})(self);(function(a){a.Object.values||a.Object.defineProperty(a.Object,"values",{configurable:!0,writable:!0,value:da})})(self);var r="undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:{};function t(a,b){b=b.split(":")[0];a=+a;if(!a)return!1;switch(b){case "http":case "ws":return 80!==a;case "https":case "wss":return 443!==a;case "ftp":return 21!==a;case "gopher":return 70!==a;case "file":return!1}return 0!==a}var ea=Object.prototype.hasOwnProperty;
function fa(a,b){b=b||"";var c=[];"string"!==typeof b&&(b="?");for(var d in a)ea.call(a,d)&&c.push(encodeURIComponent(d)+"="+encodeURIComponent(a[d]));return c.length?b+c.join("&"):""}function v(a){for(var b=/([^=?&]+)=?([^&]*)/g,c={},d;d=b.exec(a);){var e=decodeURIComponent(d[1].replace(/\+/g," "));d=decodeURIComponent(d[2].replace(/\+/g," "));e in c||(c[e]=d)}return c}
var ha=/^([a-z][a-z0-9.+-]*:)?(\/\/)?([\S\s]*)/i,ia=/^[A-Za-z][A-Za-z0-9+-.]*:\/\//,x=[["#","hash"],["?","query"],function(a){return a.replace("\\","/")},["/","pathname"],["@","auth",1],[NaN,"host",void 0,1,1],[/:(\d+)$/,"port",void 0,1],[NaN,"hostname",void 0,1,1]],y={hash:1,query:1};
function z(a,b,c){if(!(this instanceof z))return new z(a,b,c);var d=x.slice(),e=typeof b,f=0;"object"!==e&&"string"!==e&&(c=b,b=null);c&&"function"!==typeof c&&(c=v);e=r&&r.location||{};b=b||e;e={};var g=typeof b;if("blob:"===b.protocol)e=new z(unescape(b.pathname),{});else if("string"===g)for(h in e=new z(b,{}),y)delete e[h];else if("object"===g){for(h in b)h in y||(e[h]=b[h]);void 0===e.slashes&&(e.slashes=ia.test(b.href))}b=e;var h=ha.exec(a||"");a=h[1]?h[1].toLowerCase():"";e=!!h[2];g=h[3];h=
!a&&!e;this.slashes=e||h&&b.slashes;this.protocol=a||b.protocol||"";a=g;for(e||(d[3]=[/(.*)/,"pathname"]);f<d.length;f++)if(e=d[f],"function"===typeof e)a=e(a);else{var k=e[0];g=e[1];if(k!==k)this[g]=a;else if("string"===typeof k)~(k=a.indexOf(k))&&("number"===typeof e[2]?(this[g]=a.slice(0,k),a=a.slice(k+e[2])):(this[g]=a.slice(k),a=a.slice(0,k)));else if(k=k.exec(a))this[g]=k[1],a=a.slice(0,k.index);this[g]=this[g]||(h&&e[3]?b[g]||"":"");e[4]&&(this[g]=this[g].toLowerCase())}c&&(this.query=c(this.query));
if(h&&b.slashes&&"/"!==this.pathname.charAt(0)&&(""!==this.pathname||""!==b.pathname)){c=this.pathname;c=(b.pathname||"/").split("/").slice(0,-1).concat(c.split("/"));d=c.length;f=c[d-1];b=!1;for(a=0;d--;)"."===c[d]?c.splice(d,1):".."===c[d]?(c.splice(d,1),a++):a&&(0===d&&(b=!0),c.splice(d,1),a--);b&&c.unshift("");"."!==f&&".."!==f||c.push("");this.pathname=c.join("/")}t(this.port,this.protocol)||(this.host=this.hostname,this.port="");this.username=this.password="";this.auth&&(e=this.auth.split(":"),
this.username=e[0]||"",this.password=e[1]||"");this.origin=this.protocol&&this.host&&"file:"!==this.protocol?this.protocol+"//"+this.host:"null";this.href=this.toString()}
z.prototype={set:function(a,b,c){switch(a){case "query":"string"===typeof b&&b.length&&(b=(c||v)(b));this[a]=b;break;case "port":this[a]=b;t(b,this.protocol)?b&&(this.host=this.hostname+":"+b):(this.host=this.hostname,this[a]="");break;case "hostname":this[a]=b;this.port&&(b+=":"+this.port);this.host=b;break;case "host":this[a]=b;/:\d+$/.test(b)?(b=b.split(":"),this.port=b.pop(),this.hostname=b.join(":")):(this.hostname=b,this.port="");break;case "protocol":this.protocol=b.toLowerCase();this.slashes=
!c;break;case "pathname":case "hash":b?(c="pathname"===a?"/":"#",this[a]=b.charAt(0)!==c?c+b:b):this[a]=b;break;default:this[a]=b}for(a=0;a<x.length;a++)b=x[a],b[4]&&(this[b[1]]=this[b[1]].toLowerCase());this.origin=this.protocol&&this.host&&"file:"!==this.protocol?this.protocol+"//"+this.host:"null";this.href=this.toString();return this},toString:function(a){a&&"function"===typeof a||(a=fa);var b=this.protocol;b&&":"!==b.charAt(b.length-1)&&(b+=":");b+=this.slashes?"//":"";this.username&&(b+=this.username,
this.password&&(b+=":"+this.password),b+="@");b+=this.host+this.pathname;(a="object"===typeof this.query?a(this.query):this.query)&&(b+="?"!==a.charAt(0)?"?"+a:a);this.hash&&(b+=this.hash);return b}};var ja=/^xn--/,ka=/[^\x20-\x7E]/,la=/[\x2E\u3002\uFF0E\uFF61]/g,ma={overflow:"Overflow: input needs wider integers to process","not-basic":"Illegal input >= 0x80 (not a basic code point)","invalid-input":"Invalid input"},A=Math.floor,B=String.fromCharCode;function C(a){throw new RangeError(ma[a]);}
function D(a,b){for(var c=a.length,d=[];c--;)d[c]=b(a[c]);return d}function E(a,b){var c=a.split("@"),d="";1<c.length&&(d=c[0]+"@",a=c[1]);a=a.replace(la,".");a=a.split(".");b=D(a,b).join(".");return d+b}function na(a){return D(a,function(a){var b="";65535<a&&(a-=65536,b+=B(a>>>10&1023|55296),a=56320|a&1023);return b+B(a)}).join("")}function F(a){return a+22+75*(26>a)-0}function G(a,b,c){var d=0;a=c?A(a/700):a>>1;for(a+=A(a/b);455<a;d+=36)a=A(a/35);return A(d+36*a/(a+38))}
function oa(a){return E(a,function(a){if(ka.test(a)){var b;var d=[];var e=[];var f=0;for(var g=a.length,h;f<g;)h=a.charCodeAt(f++),55296<=h&&56319>=h&&f<g?(b=a.charCodeAt(f++),56320==(b&64512)?e.push(((h&1023)<<10)+(b&1023)+65536):(e.push(h),f--)):e.push(h);b=e;g=b.length;h=128;var k=0,p=72;for(f=0;f<g;++f){var m=b[f];128>m&&d.push(B(m))}for((a=e=d.length)&&d.push("-");a<g;){var n=2147483647;for(f=0;f<g;++f)m=b[f],m>=h&&m<n&&(n=m);var w=a+1;n-h>A((2147483647-k)/w)&&C("overflow");k+=(n-h)*w;h=n;for(f=
0;f<g;++f)if(m=b[f],m<h&&2147483647<++k&&C("overflow"),m==h){var u=k;for(n=36;;n+=36){m=n<=p?1:n>=p+26?26:n-p;if(u<m)break;var X=u-m;u=36-m;d.push(B(F(m+X%u)));u=A(X/u)}d.push(B(F(u)));p=G(k,w,a==e);k=0;++a}++k;++h}d="xn--"+d.join("")}else d=a;return d})}
function H(a){return E(a,function(a){if(ja.test(a)){a=a.slice(4).toLowerCase();var b=[],d=a.length,e=0,f=128,g=72,h,k,p=a.lastIndexOf("-");0>p&&(p=0);for(h=0;h<p;++h)128<=a.charCodeAt(h)&&C("not-basic"),b.push(a.charCodeAt(h));for(p=0<p?p+1:0;p<d;){h=e;var m=1;for(k=36;;k+=36){p>=d&&C("invalid-input");var n=a.charCodeAt(p++);n=10>n-48?n-22:26>n-65?n-65:26>n-97?n-97:36;(36<=n||n>A((2147483647-e)/m))&&C("overflow");e+=n*m;var w=k<=g?1:k>=g+26?26:k-g;if(n<w)break;n=36-w;m>A(2147483647/n)&&C("overflow");
m*=n}m=b.length+1;g=G(e-h,m,0==h);A(e/m)>2147483647-f&&C("overflow");f+=A(e/m);e%=m;b.splice(e++,0,f)}a=na(b)}return a})}var pa=/[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]/,qa=/[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]/;
function ra(a){a=(new z(a)).hostname;var b=H(a);return!(63>=a.length)||pa.test(b)&&qa.test(b)||-1==a.indexOf(".")?I(a):(b=H(a),b=b.split("-").join("--"),b=b.split(".").join("-"),b=oa(b).toLowerCase(),63<b.length?I(a):Promise.resolve(b))}function I(a){return sa(a).then(function(a){return ta("ffffffffff"+a+"000000").substr(8,Math.ceil(4*a.length/5))})}
function sa(a){if("undefined"!==typeof window)return a=(new TextEncoder("utf-8")).encode(a),crypto.subtle.digest("SHA-256",a).then(function(a){var b=[];a=new DataView(a);for(var c=0;c<a.byteLength;c+=4){var d=("00000000"+a.getUint32(c).toString(16)).slice(-8);b.push(d)}return b.join("")});var b=Buffer.from(a,"utf-8"),c={};return new Promise(function(a){var d=c.createHash("sha256").update(b).digest("hex");a(d)})}
function ta(a){var b=[];a.match(/.{1,2}/g).forEach(function(a,c){b[c]=parseInt(a,16)});var c=b.length%5,d=Math.floor(b.length/5);a=[];if(0!=c){for(var e=0;e<5-c;e++)b+="\x00";d+=1}for(e=0;e<d;e++)a.push("abcdefghijklmnopqrstuvwxyz234567".charAt(b[5*e]>>3)),a.push("abcdefghijklmnopqrstuvwxyz234567".charAt((b[5*e]&7)<<2|b[5*e+1]>>6)),a.push("abcdefghijklmnopqrstuvwxyz234567".charAt((b[5*e+1]&63)>>1)),a.push("abcdefghijklmnopqrstuvwxyz234567".charAt((b[5*e+1]&1)<<4|b[5*e+2]>>4)),a.push("abcdefghijklmnopqrstuvwxyz234567".charAt((b[5*
e+2]&15)<<1|b[5*e+3]>>7)),a.push("abcdefghijklmnopqrstuvwxyz234567".charAt((b[5*e+3]&127)>>2)),a.push("abcdefghijklmnopqrstuvwxyz234567".charAt((b[5*e+3]&3)<<3|b[5*e+4]>>5)),a.push("abcdefghijklmnopqrstuvwxyz234567".charAt(b[5*e+4]&31));d=0;1==c?d=6:2==c?d=4:3==c?d=3:4==c&&(d=1);for(c=0;c<d;c++)a.pop();for(c=0;c<d;c++)a.push("=");return a.join("")};function ua(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var va=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function wa(a){var b=Object.create(null);if(!a)return b;for(var c;c=va.exec(a);){var d=ua(c[1],c[1]),e=c[2]?ua(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var J="";
function K(a){var b=a||self;if(b.__AMP_MODE)b=b.__AMP_MODE;else{var c=wa(b.location.originalHash||b.location.hash);var d=wa(b.location.search);J||(J=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012007102309000");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(c.development)||b.AMP_DEV_MODE),examiner:"2"==c.development,esm:!1,geoOverride:c["amp-geo"],minified:!0,lite:void 0!=d.amp_lite,test:!1,log:c.log,version:"2007102309000",rtvVersion:J};b=b.__AMP_MODE=c}return b}
;function xa(a){var b=!1,c=null,d=a;return function(a){for(var e=[],g=0;g<arguments.length;++g)e[g-0]=arguments[g];b||(c=d.apply(self,e),b=!0,d=null);return c}};var L=self.AMP_CONFIG||{},ya=("string"==typeof L.cdnProxyRegex?new RegExp(L.cdnProxyRegex):L.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function za(a){if(!self.document||!self.document.head||self.location&&ya.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var Aa={thirdParty:L.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:L.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof L.thirdPartyFrameRegex?new RegExp(L.thirdPartyFrameRegex):L.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:L.cdnUrl||za("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ya,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:L.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:L.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:L.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:L.geoApiUrl||za("amp-geo-api")};function Ba(){}function Ca(a,b){return b.reduce(function(a,b){return a+"&s[]="+encodeURIComponent(String(Da(b)))},"https://log.amp.dev/?v=012007102309000&id="+encodeURIComponent(a))}
function Ea(a,b,c){var d=this;c=void 0===c?"":c;this.win=a;this.J=b;this.l=this.win.console&&this.win.console.log&&"0"!=K().log?this.J(parseInt(K().log,10),K().development):0;this.A=c;this.w=null;this.I=xa(function(){a.fetch(Aa.cdn+"/rtv/012007102309000/log-messages.simple.json").then(function(a){return a.json()},Ba).then(function(a){a&&(d.w=a)})})}
function M(a,b,c,d){if(0!=a.l){var e=a.win.console.log;"ERROR"==c?e=a.win.console.error||e:"INFO"==c?e=a.win.console.info||e:"WARN"==c&&(e=a.win.console.warn||e);c=Array.isArray(d[0])?Fa(a,d[0]):d;b="["+b+"]";"string"===typeof c[0]?c[0]=b+" "+c[0]:c.unshift(b);e.apply(a.win.console,c)}}l=Ea.prototype;l.isEnabled=function(){return 0!=this.l};l.fine=function(a,b){4<=this.l&&M(this,a,"FINE",Array.prototype.slice.call(arguments,1))};
l.info=function(a,b){3<=this.l&&M(this,a,"INFO",Array.prototype.slice.call(arguments,1))};l.warn=function(a,b){2<=this.l&&M(this,a,"WARN",Array.prototype.slice.call(arguments,1))};l.G=function(a,b){if(1<=this.l)M(this,a,"ERROR",Array.prototype.slice.call(arguments,1));else{var c=N.apply(null,Array.prototype.slice.call(arguments,1));O(this,c);return c}};l.error=function(a,b){var c=this.G.apply(this,arguments);c&&(c.name=a||c.name,self.__AMP_REPORT_ERROR(c))};
l.expectedError=function(a,b){var c=this.G.apply(this,arguments);c&&(c.expected=!0,self.__AMP_REPORT_ERROR(c))};l.createError=function(a){var b=N.apply(null,arguments);O(this,b);return b};l.createExpectedError=function(a){var b=N.apply(null,arguments);O(this,b);b.expected=!0;return b};
l.assert=function(a,b,c){var d;if(Array.isArray(b))return this.assert.apply(this,[a].concat(Fa(this,b)));if(!a){var e=(b||"Assertion failed").split("%s"),f=e.shift(),g=f,h=[],k=2;for(""!=f&&h.push(f);0<e.length;){var p=e.shift(),m=arguments[k++];m&&m.tagName&&(d=m);h.push(m);f=p.trim();""!=f&&h.push(f);g+=Da(m)+p}k=Error(g);k.fromAssert=!0;k.associatedElement=d;k.messageArray=h;O(this,k);self.__AMP_REPORT_ERROR(k);throw k;}return a};
l.assertElement=function(a,b){P(this,a,a&&1==a.nodeType,"Element expected",b);return a};l.assertString=function(a,b){P(this,a,"string"==typeof a,"String expected",b);return a};l.assertNumber=function(a,b){P(this,a,"number"==typeof a,"Number expected",b);return a};l.assertArray=function(a,b){P(this,a,Array.isArray(a),"Array expected",b);return a};l.assertBoolean=function(a,b){P(this,a,!!a===a,"Boolean expected",b);return a};
l.assertEnumValue=function(a,b,c){a:{for(var d in a)if(a[d]===b){a=!0;break a}a=!1}if(a)return b;this.assert(!1,'Unknown %s value: "%s"',c||"enum",b)};function O(a,b){b=Ga(b);a.A?b.message?-1==b.message.indexOf(a.A)&&(b.message+=a.A):b.message=a.A:0<=b.message.indexOf("\u200b\u200b\u200b")&&(b.message=b.message.replace("\u200b\u200b\u200b",""))}function Fa(a,b){var c=b.shift();K(a.win).development&&a.I();return a.w&&c in a.w?[a.w[c]].concat(b):["More info at "+Ca(c,b)]}
function P(a,b,c,d,e){Array.isArray(e)?a.assert(c,e.concat(b)):a.assert(c,(e||d)+": %s",b)}function Da(a){return a&&1==a.nodeType?a.tagName.toLowerCase()+(a.id?"#"+a.id:""):a}function Ga(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}
function N(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=Ga(e):(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var Q=self.__AMP_LOG,R=null;function Ha(){Q.user||(Q.user=Ia());return Q.user}function Ia(){if(!R)throw Error("failed to call initLogConstructor");return new R(self,function(a,b){return b||1<=a?4:2},"\u200b\u200b\u200b")}
function S(){if(Q.dev)return Q.dev;if(!R)throw Error("failed to call initLogConstructor");return Q.dev=new R(self,function(a){return 3<=a?4:2<=a?3:0})}function Ja(){};var Ka=Object.prototype.hasOwnProperty;function T(a){return a||{}};var U;function La(a,b){var c=Ma();a.addEventListener("message",function(a){try{return b(a)}catch(e){throw self.__AMP_REPORT_ERROR(e),e;}},c?void 0:!1)}function Ma(){if(void 0!==U)return U;U=!1;try{var a={get capture(){U=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return U};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Na(a,b){La(a,b)};function Oa(){this.h=null}l=Oa.prototype;l.add=function(a){var b=this;this.h||(this.h=[]);this.h.push(a);return function(){b.remove(a)}};l.remove=function(a){this.h&&(a=this.h.indexOf(a),-1<a&&this.h.splice(a,1))};l.removeAll=function(){this.h&&(this.h.length=0)};l.fire=function(a){if(this.h)for(var b=this.h,c=0;c<b.length;c++)(0,b[c])(a)};l.getHandlerCount=function(){return this.h?this.h.length:0};function Pa(a,b){this.F=a;this.L=K().rtvVersion||null;this.j=b||null;this.C=null;this.K=1;this.m=Object.create(null);Qa(this)}l=Pa.prototype;l.getData=function(a,b,c){var d=a+"-result",e=this.K++,f=this.registerCallback(d,function(a){a.messageId===e&&(f(),c(a.content))}),g={};g.payload=b;g.messageId=e;this.sendMessage(a,g)};l.makeRequest=function(a,b,c){b=this.registerCallback(b,c);this.sendMessage(a);return b};
l.requestOnce=function(a,b,c){var d=this.registerCallback(b,function(a){d();c(a)});this.sendMessage(a);return d};l.registerCallback=function(a,b){a in this.m||(this.m[a]=new Oa);return this.m[a].add(b)};
l.sendMessage=function(a,b){var c=this.C,d=b,e=this.L;d=void 0===d?{}:d;d.type=a;d.sentinel=c;a="amp-"+((void 0===e?null:e)||"")+JSON.stringify(d);if(this.j)c=this.j,1==c.postMessage.length?Ra(c,a):c.postMessage(a,"*");else for(var f=0,g=this.F;10>f&&g!=this.F.top;f++)c=g=g.parent,e=a,1==c.postMessage.length?Ra(c,e):c.postMessage(e,"*"),f++};function Ra(a,b){a.postMessage(b,T({targetOrigin:"*",includeUserActivation:!0}))}
function Qa(a){Na(a.F,function(b){if(!a.j||b.source==a.j){var c=b.data;if("string"==typeof c&&0==c.indexOf("amp-")&&-1!=c.indexOf("{")){var d=c.indexOf("{");try{var e=JSON.parse(c.substr(d))}catch(f){S().error("MESSAGING","Failed to parse message: "+c,f),e=null}}else e=null;e&&e.sentinel==a.C&&(e.origin=b.origin,a.j||(a.j=b.source),b=e.type,b in a.m&&a.m[b].fire(e))}})}l.setSentinel=function(a){this.C=a};function V(){this.H=100;this.B=this.D=0;this.o=Object.create(null)}V.prototype.has=function(a){return!!this.o[a]};V.prototype.get=function(a){var b=this.o[a];if(b)return b.access=++this.B,b.payload};V.prototype.put=function(a,b){this.has(a)||this.D++;this.o[a]={payload:b,access:this.B};if(!(this.D<=this.H)){S().warn("lru-cache","Trimming LRU cache");a=this.o;b=this.B+1;var c;for(c in a){var d=a[c].access;if(d<b){b=d;var e=c}}void 0!==e&&(delete a[e],this.D--)}};T({c:!0,v:!0,a:!0,ad:!0,action:!0});var W,Sa;
function Ta(a){W||(W=self.document.createElement("a"),Sa=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new V));var b=Sa,c=W;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}function Ua(a){"string"==typeof a&&(a=Ta(a));return Aa.cdnProxyRegex.test(a.origin)};function Va(a,b,c,d){var e=a.document.createElement("script");e.src=b;c&&(e.onload=c);d&&(e.onerror=d);a.document.body.appendChild(e)};var Y=null,Z=null;(function(){R=Ea;S();Ha();var a=console.error.bind(console);self.__AMP_REPORT_ERROR=a})();
window.initRecaptcha=function(a){a=void 0===a?"https://www.google.com/recaptcha/api.js?render=":a;var b=window;try{var c=JSON.parse(b.name)}catch(d){throw Error("RECAPTCHA Could not parse the window name.");}Z=c.sitekey;Ja(Ka.call(c,"global"));c.global&&(a="https://www.recaptcha.net/recaptcha/api.js?render=");Va(b,a+Z,function(){var a=b.grecaptcha;a.ready(function(){Wa(b,a,c);Y.sendMessage("amp-recaptcha-ready")})},function(){S().error("RECAPTCHA Failed to load recaptcha api script")})};
function Wa(a,b,c){Y=new Pa(a,a.parent);Y.setSentinel(c.sentinel);Y.registerCallback("amp-recaptcha-action",Xa.bind(this,a,b))}
function Xa(a,b,c){Ya(a,c).then(function(){b.execute(Z,{action:c.action}).then(function(a){Y.sendMessage("amp-recaptcha-token",T({id:c.id,token:a}))},function(a){var b="There was an error running execute() on the reCAPTCHA script.";a&&(b=a.toString());Ha().error("RECAPTCHA","%s",b);Y.sendMessage("amp-recaptcha-error",T({id:c.id,error:b}))})}).catch(function(a){S().error("RECAPTCHA","%s",a.message)})}
function Ya(a,b){if(!b.origin)return Promise.reject(Error("Could not retreive the origin domain"));var c=Ta(b.origin);if(Ua(b.origin)){var d=c.hostname.split(".")[0];return Za(a,d,b.origin)}return ra(b.origin).then(function(c){return Za(a,c,b.origin)})}function Za(a,b,c){var d=a.location.hostname.split(".").slice(1).join(".");b+"."+d===a.location.hostname?(q||(q=Promise.resolve(void 0)),a=q):a=Promise.reject(Error("Origin domain does not match Iframe src: "+c));return a};})();

//# sourceMappingURL=recaptcha.js.map
