/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};
$jscomp.getConstructImplementation=function(){function a(){function a(){}new a;Reflect.construct(a,[],function(){});return new a instanceof a}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(a,d,e){a=b(a,d);e&&Reflect.setPrototypeOf(a,e.prototype);return a}}return function(a,b,e){void 0===e&&(e=a);e=$jscomp.objectCreate(e.prototype||Object.prototype);return Function.prototype.apply.call(a,e,b)||
e}};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,b)}else for(c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype};$jscomp.polyfill("Reflect",function(a){return a?a:{}},"es6","es3");$jscomp.polyfill("Reflect.construct",function(a){return $jscomp.construct},"es6","es3");
$jscomp.polyfill("Reflect.setPrototypeOf",function(a){if(a)return a;if($jscomp.setPrototypeOf){var b=$jscomp.setPrototypeOf;return function(a,d){try{return b(a,d),!0}catch(e){return!1}}}return null},"es6","es5");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).i}},"es6","es3");var COMPILED=!0,goog=goog||{};goog.global=this||self;goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};
goog.define=function(a,b){if(!COMPILED){var c=goog.global.CLOSURE_UNCOMPILED_DEFINES,d=goog.global.CLOSURE_DEFINES;c&&void 0===c.nodeType&&Object.prototype.hasOwnProperty.call(c,a)?b=c[a]:d&&void 0===d.nodeType&&Object.prototype.hasOwnProperty.call(d,a)&&(b=d[a])}return b};goog.FEATURESET_YEAR=2012;goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.DISALLOW_TEST_ONLY_CODE=COMPILED&&!goog.DEBUG;goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING=!1;
goog.provide=function(a){if(goog.isInModuleLoader_())throw Error("goog.provide cannot be used within a module.");if(!COMPILED&&goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');goog.constructNamespace_(a)};goog.constructNamespace_=function(a,b){if(!COMPILED){delete goog.implicitNamespaces_[a];for(var c=a;(c=c.substring(0,c.lastIndexOf(".")))&&!goog.getObjectByName(c);)goog.implicitNamespaces_[c]=!0}goog.exportPath_(a,b)};
goog.getScriptNonce=function(a){if(a&&a!=goog.global)return goog.getScriptNonce_(a.document);null===goog.cspNonce_&&(goog.cspNonce_=goog.getScriptNonce_(goog.global.document));return goog.cspNonce_};goog.NONCE_PATTERN_=/^[\w+/_-]+[=]{0,2}$/;goog.cspNonce_=null;goog.getScriptNonce_=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&goog.NONCE_PATTERN_.test(a)?a:""};goog.VALID_MODULE_RE_=/^[a-zA-Z_$][a-zA-Z0-9._$]*$/;
goog.module=function(a){if("string"!==typeof a||!a||-1==a.search(goog.VALID_MODULE_RE_))throw Error("Invalid module identifier");if(!goog.isInGoogModuleLoader_())throw Error("Module "+a+" has been loaded incorrectly. Note, modules cannot be loaded as normal scripts. They require some kind of pre-processing step. You're likely trying to load a module via a script tag or as a part of a concatenated bundle without rewriting the module. For more info see: https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide.");
if(goog.moduleLoaderState_.moduleName)throw Error("goog.module may only be called once per module.");goog.moduleLoaderState_.moduleName=a;if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a]}};goog.module.get=function(a){return goog.module.getInternal_(a)};
goog.module.getInternal_=function(a){if(!COMPILED){if(a in goog.loadedModules_)return goog.loadedModules_[a].exports;if(!goog.implicitNamespaces_[a])return a=goog.getObjectByName(a),null!=a?a:null}return null};goog.ModuleType={ES6:"es6",GOOG:"goog"};goog.moduleLoaderState_=null;goog.isInModuleLoader_=function(){return goog.isInGoogModuleLoader_()||goog.isInEs6ModuleLoader_()};goog.isInGoogModuleLoader_=function(){return!!goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.GOOG};
goog.isInEs6ModuleLoader_=function(){if(goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.ES6)return!0;var a=goog.global.$jscomp;return a?"function"!=typeof a.getCurrentModulePath?!1:!!a.getCurrentModulePath():!1};
goog.module.declareLegacyNamespace=function(){if(!COMPILED&&!goog.isInGoogModuleLoader_())throw Error("goog.module.declareLegacyNamespace must be called from within a goog.module");if(!COMPILED&&!goog.moduleLoaderState_.moduleName)throw Error("goog.module must be called prior to goog.module.declareLegacyNamespace.");goog.moduleLoaderState_.declareLegacyNamespace=!0};
goog.declareModuleId=function(a){if(!COMPILED){if(!goog.isInEs6ModuleLoader_())throw Error("goog.declareModuleId may only be called from within an ES6 module");if(goog.moduleLoaderState_&&goog.moduleLoaderState_.moduleName)throw Error("goog.declareModuleId may only be called once per module.");if(a in goog.loadedModules_)throw Error('Module with namespace "'+a+'" already exists.');}if(goog.moduleLoaderState_)goog.moduleLoaderState_.moduleName=a;else{var b=goog.global.$jscomp;if(!b||"function"!=typeof b.getCurrentModulePath)throw Error('Module with namespace "'+
a+'" has been loaded incorrectly.');b=b.require(b.getCurrentModulePath());goog.loadedModules_[a]={exports:b,type:goog.ModuleType.ES6,moduleId:a}}};goog.setTestOnly=function(a){if(goog.DISALLOW_TEST_ONLY_CODE)throw a=a||"",Error("Importing test-only code into non-debug environment"+(a?": "+a:"."));};goog.forwardDeclare=function(a){};COMPILED||(goog.isProvided_=function(a){return a in goog.loadedModules_||!goog.implicitNamespaces_[a]&&null!=goog.getObjectByName(a)},goog.implicitNamespaces_={"goog.module":!0});
goog.getObjectByName=function(a,b){a=a.split(".");b=b||goog.global;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};goog.addDependency=function(a,b,c,d){!COMPILED&&goog.DEPENDENCIES_ENABLED&&goog.debugLoader_.addDependency(a,b,c,d)};goog.ENABLE_DEBUG_LOADER=!0;goog.logToConsole_=function(a){goog.global.console&&goog.global.console.error(a)};
goog.require=function(a){if(!COMPILED){goog.ENABLE_DEBUG_LOADER&&goog.debugLoader_.requested(a);if(goog.isProvided_(a)){if(goog.isInModuleLoader_())return goog.module.getInternal_(a)}else if(goog.ENABLE_DEBUG_LOADER){var b=goog.moduleLoaderState_;goog.moduleLoaderState_=null;try{goog.debugLoader_.load_(a)}finally{goog.moduleLoaderState_=b}}return null}};goog.requireType=function(a){return{}};goog.basePath="";goog.nullFunction=function(){};
goog.abstractMethod=function(){throw Error("unimplemented abstract method");};goog.addSingletonGetter=function(a){a.instance_=void 0;a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];goog.LOAD_MODULE_USING_EVAL=!0;goog.SEAL_MODULE_EXPORTS=goog.DEBUG;goog.loadedModules_={};goog.DEPENDENCIES_ENABLED=!COMPILED&&goog.ENABLE_DEBUG_LOADER;goog.TRANSPILE="detect";
goog.ASSUME_ES_MODULES_TRANSPILED=!1;goog.TRANSPILE_TO_LANGUAGE="";goog.TRANSPILER="transpile.js";goog.hasBadLetScoping=null;goog.useSafari10Workaround=function(){if(null==goog.hasBadLetScoping){try{var a=!eval('"use strict";let x = 1; function f() { return typeof x; };f() == "number";')}catch(b){a=!1}goog.hasBadLetScoping=a}return goog.hasBadLetScoping};goog.workaroundSafari10EvalBug=function(a){return"(function(){"+a+"\n;})();\n"};
goog.loadModule=function(a){var b=goog.moduleLoaderState_;try{goog.moduleLoaderState_={moduleName:"",declareLegacyNamespace:!1,type:goog.ModuleType.GOOG};if(goog.isFunction(a))var c=a.call(void 0,{});else if("string"===typeof a)goog.useSafari10Workaround()&&(a=goog.workaroundSafari10EvalBug(a)),c=goog.loadModuleFromSource_.call(void 0,a);else throw Error("Invalid module definition");var d=goog.moduleLoaderState_.moduleName;if("string"===typeof d&&d)goog.moduleLoaderState_.declareLegacyNamespace?goog.constructNamespace_(d,
c):goog.SEAL_MODULE_EXPORTS&&Object.seal&&"object"==typeof c&&null!=c&&Object.seal(c),goog.loadedModules_[d]={exports:c,type:goog.ModuleType.GOOG,moduleId:goog.moduleLoaderState_.moduleName};else throw Error('Invalid module name "'+d+'"');}finally{goog.moduleLoaderState_=b}};goog.loadModuleFromSource_=function(a){eval(a);return{}};goog.normalizePath_=function(a){a=a.split("/");for(var b=0;b<a.length;)"."==a[b]?a.splice(b,1):b&&".."==a[b]&&a[b-1]&&".."!=a[b-1]?a.splice(--b,2):b++;return a.join("/")};
goog.loadFileSync_=function(a){if(goog.global.CLOSURE_LOAD_FILE_SYNC)return goog.global.CLOSURE_LOAD_FILE_SYNC(a);try{var b=new goog.global.XMLHttpRequest;b.open("get",a,!1);b.send();return 0==b.status||200==b.status?b.responseText:null}catch(c){return null}};
goog.transpile_=function(a,b,c){var d=goog.global.$jscomp;d||(goog.global.$jscomp=d={});var e=d.transpile;if(!e){var f=goog.basePath+goog.TRANSPILER,g=goog.loadFileSync_(f);if(g){(function(){(0,eval)(g+"\n//# sourceURL="+f)}).call(goog.global);if(goog.global.$gwtExport&&goog.global.$gwtExport.$jscomp&&!goog.global.$gwtExport.$jscomp.transpile)throw Error('The transpiler did not properly export the "transpile" method. $gwtExport: '+JSON.stringify(goog.global.$gwtExport));goog.global.$jscomp.transpile=
goog.global.$gwtExport.$jscomp.transpile;d=goog.global.$jscomp;e=d.transpile}}e||(e=d.transpile=function(a,b){goog.logToConsole_(b+" requires transpilation but no transpiler was found.");return a});return e(a,b,c)};goog.typeOf=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"};goog.isArray=function(a){return Array.isArray(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};
goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return Object.prototype.hasOwnProperty.call(a,goog.UID_PROPERTY_)&&a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.hasUid=function(a){return!!a[goog.UID_PROPERTY_]};
goog.removeUid=function(a){null!==a&&"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if("function"===typeof a.clone)return a.clone();b="array"==b?[]:{};for(var c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};goog.globalEval=function(a){(0,eval)(a)};
goog.getCssName=function(a,b){if("."==String(a).charAt(0))throw Error('className passed in goog.getCssName must not start with ".". You passed: '+a);var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")};d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a};a=b?a+"-"+d(b):d(a);return goog.global.CLOSURE_CSS_NAME_MAP_FN?goog.global.CLOSURE_CSS_NAME_MAP_FN(a):a};
goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b,c){c&&c.html&&(a=a.replace(/</g,"&lt;"));b&&(a=a.replace(/\{\$([^}]+)}/g,function(a,c){return null!=b&&c in b?b[c]:a}));return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};
goog.exportProperty=function(a,b,c){a[b]=c};goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};goog.scope=function(a){if(goog.isInModuleLoader_())throw Error("goog.scope is not supported within a module.");a.call(goog.global)};COMPILED||(goog.global.COMPILED=COMPILED);
goog.defineClass=function(a,b){var c=b.constructor,d=b.statics;c&&c!=Object.prototype.constructor||(c=function(){throw Error("cannot instantiate an interface (no constructor defined).");});c=goog.defineClass.createSealingConstructor_(c,a);a&&goog.inherits(c,a);delete b.constructor;delete b.statics;goog.defineClass.applyProperties_(c.prototype,b);null!=d&&(d instanceof Function?d(c):goog.defineClass.applyProperties_(c,d));return c};goog.defineClass.SEAL_CLASS_INSTANCES=goog.DEBUG;
goog.defineClass.createSealingConstructor_=function(a,b){return goog.defineClass.SEAL_CLASS_INSTANCES?function(){var b=a.apply(this,arguments)||this;b[goog.UID_PROPERTY_]=b[goog.UID_PROPERTY_];return b}:a};goog.defineClass.OBJECT_PROTOTYPE_FIELDS_="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
goog.defineClass.applyProperties_=function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c]);for(var d=0;d<goog.defineClass.OBJECT_PROTOTYPE_FIELDS_.length;d++)c=goog.defineClass.OBJECT_PROTOTYPE_FIELDS_[d],Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};
!COMPILED&&goog.DEPENDENCIES_ENABLED&&(goog.inHtmlDocument_=function(){var a=goog.global.document;return null!=a&&"write"in a},goog.isDocumentLoading_=function(){var a=goog.global.document;return a.attachEvent?"complete"!=a.readyState:"loading"==a.readyState},goog.findBasePath_=function(){if(void 0!=goog.global.CLOSURE_BASE_PATH&&"string"===typeof goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_()){var a=goog.global.document,b=a.currentScript;
a=b?[b]:a.getElementsByTagName("SCRIPT");for(b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?");d=-1==d?c.length:d;if("base.js"==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}}},goog.findBasePath_(),goog.Transpiler=function(){this.requiresTranspilation_=null;this.transpilationTarget_=goog.TRANSPILE_TO_LANGUAGE},goog.Transpiler.prototype.createRequiresTranspilation_=function(){function a(a,b){e?d[a]=!0:b()?(c=a,d[a]=!1):e=d[a]=!0}function b(a){try{return!!eval(a)}catch(k){return!1}}
var c="es3",d={es3:!1},e=!1,f=goog.global.navigator&&goog.global.navigator.userAgent?goog.global.navigator.userAgent:"";a("es5",function(){return b("[1,].length==1")});a("es6",function(){return f.match(/Edge\/(\d+)(\.\d)*/i)?!1:b('(()=>{"use strict";class X{constructor(){if(new.target!=String)throw 1;this.x=42}}let q=Reflect.construct(X,[],String);if(q.x!=42||!(q instanceof String))throw 1;for(const a of[2,3]){if(a==2)continue;function f(z={a}){let a=0;return z.a}{function f(){return 0;}}return f()==3}})()')});
a("es7",function(){return b("2 ** 2 == 4")});a("es8",function(){return b("async () => 1, true")});a("es9",function(){return b("({...rest} = {}), true")});a("es_next",function(){return!1});return{target:c,map:d}},goog.Transpiler.prototype.needsTranspile=function(a,b){if("always"==goog.TRANSPILE)return!0;if("never"==goog.TRANSPILE)return!1;if(!this.requiresTranspilation_){var c=this.createRequiresTranspilation_();this.requiresTranspilation_=c.map;this.transpilationTarget_=this.transpilationTarget_||
c.target}if(a in this.requiresTranspilation_)return this.requiresTranspilation_[a]?!0:!goog.inHtmlDocument_()||"es6"!=b||"noModule"in goog.global.document.createElement("script")?!1:!0;throw Error("Unknown language mode: "+a);},goog.Transpiler.prototype.transpile=function(a,b){return goog.transpile_(a,b,this.transpilationTarget_)},goog.transpiler_=new goog.Transpiler,goog.protectScriptTag_=function(a){return a.replace(/<\/(SCRIPT)/ig,"\\x3c/$1")},goog.DebugLoader_=function(){this.dependencies_={};
this.idToPath_={};this.written_={};this.loadingDeps_=[];this.depsToLoad_=[];this.paused_=!1;this.factory_=new goog.DependencyFactory(goog.transpiler_);this.deferredCallbacks_={};this.deferredQueue_=[]},goog.DebugLoader_.prototype.bootstrap=function(a,b){function c(){d&&(goog.global.setTimeout(d,0),d=null)}var d=b;if(a.length){b=[];for(var e=0;e<a.length;e++){var f=this.getPathFromDeps_(a[e]);if(!f)throw Error("Unregonized namespace: "+a[e]);b.push(this.dependencies_[f])}f=goog.require;var g=0;for(e=
0;e<a.length;e++)f(a[e]),b[e].onLoad(function(){++g==a.length&&c()})}else c()},goog.DebugLoader_.prototype.loadClosureDeps=function(){this.depsToLoad_.push(this.factory_.createDependency(goog.normalizePath_(goog.basePath+"deps.js"),"deps.js",[],[],{},!1));this.loadDeps_()},goog.DebugLoader_.prototype.requested=function(a,b){(a=this.getPathFromDeps_(a))&&(b||this.areDepsLoaded_(this.dependencies_[a].requires))&&(b=this.deferredCallbacks_[a])&&(delete this.deferredCallbacks_[a],b())},goog.DebugLoader_.prototype.setDependencyFactory=
function(a){this.factory_=a},goog.DebugLoader_.prototype.load_=function(a){if(this.getPathFromDeps_(a)){var b=this,c=[],d=function(a){var e=b.getPathFromDeps_(a);if(!e)throw Error("Bad dependency path or symbol: "+a);if(!b.written_[e]){b.written_[e]=!0;a=b.dependencies_[e];for(e=0;e<a.requires.length;e++)goog.isProvided_(a.requires[e])||d(a.requires[e]);c.push(a)}};d(a);a=!!this.depsToLoad_.length;this.depsToLoad_=this.depsToLoad_.concat(c);this.paused_||a||this.loadDeps_()}else throw a="goog.require could not find: "+
a,goog.logToConsole_(a),Error(a);},goog.DebugLoader_.prototype.loadDeps_=function(){for(var a=this,b=this.paused_;this.depsToLoad_.length&&!b;)(function(){var c=!1,d=a.depsToLoad_.shift(),e=!1;a.loading_(d);var f={pause:function(){if(c)throw Error("Cannot call pause after the call to load.");b=!0},resume:function(){c?a.resume_():b=!1},loaded:function(){if(e)throw Error("Double call to loaded.");e=!0;a.loaded_(d)},pending:function(){for(var b=[],c=0;c<a.loadingDeps_.length;c++)b.push(a.loadingDeps_[c]);
return b},setModuleState:function(a){goog.moduleLoaderState_={type:a,moduleName:"",declareLegacyNamespace:!1}},registerEs6ModuleExports:function(a,b,c){c&&(goog.loadedModules_[c]={exports:b,type:goog.ModuleType.ES6,moduleId:c||""})},registerGoogModuleExports:function(a,b){goog.loadedModules_[a]={exports:b,type:goog.ModuleType.GOOG,moduleId:a}},clearModuleState:function(){goog.moduleLoaderState_=null},defer:function(b){if(c)throw Error("Cannot register with defer after the call to load.");a.defer_(d,
b)},areDepsLoaded:function(){return a.areDepsLoaded_(d.requires)}};try{d.load(f)}finally{c=!0}})();b&&this.pause_()},goog.DebugLoader_.prototype.pause_=function(){this.paused_=!0},goog.DebugLoader_.prototype.resume_=function(){this.paused_&&(this.paused_=!1,this.loadDeps_())},goog.DebugLoader_.prototype.loading_=function(a){this.loadingDeps_.push(a)},goog.DebugLoader_.prototype.loaded_=function(a){for(var b=0;b<this.loadingDeps_.length;b++)if(this.loadingDeps_[b]==a){this.loadingDeps_.splice(b,1);
break}for(b=0;b<this.deferredQueue_.length;b++)if(this.deferredQueue_[b]==a.path){this.deferredQueue_.splice(b,1);break}if(this.loadingDeps_.length==this.deferredQueue_.length&&!this.depsToLoad_.length)for(;this.deferredQueue_.length;)this.requested(this.deferredQueue_.shift(),!0);a.loaded()},goog.DebugLoader_.prototype.areDepsLoaded_=function(a){for(var b=0;b<a.length;b++){var c=this.getPathFromDeps_(a[b]);if(!c||!(c in this.deferredCallbacks_||goog.isProvided_(a[b])))return!1}return!0},goog.DebugLoader_.prototype.getPathFromDeps_=
function(a){return a in this.idToPath_?this.idToPath_[a]:a in this.dependencies_?a:null},goog.DebugLoader_.prototype.defer_=function(a,b){this.deferredCallbacks_[a.path]=b;this.deferredQueue_.push(a.path)},goog.LoadController=function(){},goog.LoadController.prototype.pause=function(){},goog.LoadController.prototype.resume=function(){},goog.LoadController.prototype.loaded=function(){},goog.LoadController.prototype.pending=function(){},goog.LoadController.prototype.registerEs6ModuleExports=function(a,
b,c){},goog.LoadController.prototype.setModuleState=function(a){},goog.LoadController.prototype.clearModuleState=function(){},goog.LoadController.prototype.defer=function(a){},goog.LoadController.prototype.areDepsLoaded=function(){},goog.Dependency=function(a,b,c,d,e){this.path=a;this.relativePath=b;this.provides=c;this.requires=d;this.loadFlags=e;this.loaded_=!1;this.loadCallbacks_=[]},goog.Dependency.prototype.getPathName=function(){var a=this.path,b=a.indexOf("://");0<=b&&(a=a.substring(b+3),b=
a.indexOf("/"),0<=b&&(a=a.substring(b+1)));return a},goog.Dependency.prototype.onLoad=function(a){this.loaded_?a():this.loadCallbacks_.push(a)},goog.Dependency.prototype.loaded=function(){this.loaded_=!0;var a=this.loadCallbacks_;this.loadCallbacks_=[];for(var b=0;b<a.length;b++)a[b]()},goog.Dependency.defer_=!1,goog.Dependency.callbackMap_={},goog.Dependency.registerCallback_=function(a){var b=Math.random().toString(32);goog.Dependency.callbackMap_[b]=a;return b},goog.Dependency.unregisterCallback_=
function(a){delete goog.Dependency.callbackMap_[a]},goog.Dependency.callback_=function(a,b){if(a in goog.Dependency.callbackMap_){for(var c=goog.Dependency.callbackMap_[a],d=[],e=1;e<arguments.length;e++)d.push(arguments[e]);c.apply(void 0,d)}else throw Error("Callback key "+a+" does not exist (was base.js loaded more than once?).");},goog.Dependency.prototype.load=function(a){if(goog.global.CLOSURE_IMPORT_SCRIPT)goog.global.CLOSURE_IMPORT_SCRIPT(this.path)?a.loaded():a.pause();else if(goog.inHtmlDocument_()){var b=
goog.global.document;if("complete"==b.readyState&&!goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING){if(/\bdeps.js$/.test(this.path)){a.loaded();return}throw Error('Cannot write "'+this.path+'" after document load');}if(!goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING&&goog.isDocumentLoading_()){var c=goog.Dependency.registerCallback_(function(b){goog.DebugLoader_.IS_OLD_IE_&&"complete"!=b.readyState||(goog.Dependency.unregisterCallback_(c),a.loaded())}),d=!goog.DebugLoader_.IS_OLD_IE_&&goog.getScriptNonce()?
' nonce="'+goog.getScriptNonce()+'"':"";d='<script src="'+this.path+'" '+(goog.DebugLoader_.IS_OLD_IE_?"onreadystatechange":"onload")+"=\"goog.Dependency.callback_('"+c+'\', this)" type="text/javascript" '+(goog.Dependency.defer_?"defer":"")+d+">\x3c/script>";b.write(goog.TRUSTED_TYPES_POLICY_?goog.TRUSTED_TYPES_POLICY_.createHTML(d):d)}else{var e=b.createElement("script");e.defer=goog.Dependency.defer_;e.async=!1;e.type="text/javascript";(d=goog.getScriptNonce())&&e.setAttribute("nonce",d);goog.DebugLoader_.IS_OLD_IE_?
(a.pause(),e.onreadystatechange=function(){if("loaded"==e.readyState||"complete"==e.readyState)a.loaded(),a.resume()}):e.onload=function(){e.onload=null;a.loaded()};e.src=goog.TRUSTED_TYPES_POLICY_?goog.TRUSTED_TYPES_POLICY_.createScriptURL(this.path):this.path;b.head.appendChild(e)}}else goog.logToConsole_("Cannot use default debug loader outside of HTML documents."),"deps.js"==this.relativePath?(goog.logToConsole_("Consider setting CLOSURE_IMPORT_SCRIPT before loading base.js, or setting CLOSURE_NO_DEPS to true."),
a.loaded()):a.pause()},goog.Es6ModuleDependency=function(a,b,c,d,e){goog.Dependency.call(this,a,b,c,d,e)},goog.inherits(goog.Es6ModuleDependency,goog.Dependency),goog.Es6ModuleDependency.prototype.load=function(a){function b(a,b){a=b?'<script type="module" crossorigin>'+b+"\x3c/script>":'<script type="module" crossorigin src="'+a+'">\x3c/script>';d.write(goog.TRUSTED_TYPES_POLICY_?goog.TRUSTED_TYPES_POLICY_.createHTML(a):a)}function c(a,b){var c=d.createElement("script");c.defer=!0;c.async=!1;c.type=
"module";c.setAttribute("crossorigin",!0);var e=goog.getScriptNonce();e&&c.setAttribute("nonce",e);b?c.textContent=goog.TRUSTED_TYPES_POLICY_?goog.TRUSTED_TYPES_POLICY_.createScript(b):b:c.src=goog.TRUSTED_TYPES_POLICY_?goog.TRUSTED_TYPES_POLICY_.createScriptURL(a):a;d.head.appendChild(c)}if(goog.global.CLOSURE_IMPORT_SCRIPT)goog.global.CLOSURE_IMPORT_SCRIPT(this.path)?a.loaded():a.pause();else if(goog.inHtmlDocument_()){var d=goog.global.document,e=this;if(goog.isDocumentLoading_()){var f=b;goog.Dependency.defer_=
!0}else f=c;var g=goog.Dependency.registerCallback_(function(){goog.Dependency.unregisterCallback_(g);a.setModuleState(goog.ModuleType.ES6)});f(void 0,'goog.Dependency.callback_("'+g+'")');f(this.path,void 0);var k=goog.Dependency.registerCallback_(function(b){goog.Dependency.unregisterCallback_(k);a.registerEs6ModuleExports(e.path,b,goog.moduleLoaderState_.moduleName)});f(void 0,'import * as m from "'+this.path+'"; goog.Dependency.callback_("'+k+'", m)');var h=goog.Dependency.registerCallback_(function(){goog.Dependency.unregisterCallback_(h);
a.clearModuleState();a.loaded()});f(void 0,'goog.Dependency.callback_("'+h+'")')}else goog.logToConsole_("Cannot use default debug loader outside of HTML documents."),a.pause()},goog.TransformedDependency=function(a,b,c,d,e){goog.Dependency.call(this,a,b,c,d,e);this.contents_=null;this.lazyFetch_=!goog.inHtmlDocument_()||!("noModule"in goog.global.document.createElement("script"))},goog.inherits(goog.TransformedDependency,goog.Dependency),goog.TransformedDependency.prototype.load=function(a){function b(){e.contents_=
goog.loadFileSync_(e.path);e.contents_&&(e.contents_=e.transform(e.contents_),e.contents_&&(e.contents_+="\n//# sourceURL="+e.path))}function c(){e.lazyFetch_&&b();if(e.contents_){f&&a.setModuleState(goog.ModuleType.ES6);try{var c=e.contents_;e.contents_=null;goog.globalEval(c);if(f)var d=goog.moduleLoaderState_.moduleName}finally{f&&a.clearModuleState()}f&&goog.global.$jscomp.require.ensure([e.getPathName()],function(){a.registerEs6ModuleExports(e.path,goog.global.$jscomp.require(e.getPathName()),
d)});a.loaded()}}function d(){var a=goog.global.document,b=goog.Dependency.registerCallback_(function(){goog.Dependency.unregisterCallback_(b);c()}),d='<script type="text/javascript">'+goog.protectScriptTag_('goog.Dependency.callback_("'+b+'");')+"\x3c/script>";a.write(goog.TRUSTED_TYPES_POLICY_?goog.TRUSTED_TYPES_POLICY_.createHTML(d):d)}var e=this;if(goog.global.CLOSURE_IMPORT_SCRIPT)b(),this.contents_&&goog.global.CLOSURE_IMPORT_SCRIPT("",this.contents_)?(this.contents_=null,a.loaded()):a.pause();
else{var f=this.loadFlags.module==goog.ModuleType.ES6;this.lazyFetch_||b();var g=1<a.pending().length,k=g&&goog.DebugLoader_.IS_OLD_IE_;g=goog.Dependency.defer_&&(g||goog.isDocumentLoading_());if(k||g)a.defer(function(){c()});else{var h=goog.global.document;k=goog.inHtmlDocument_()&&"ActiveXObject"in goog.global;if(f&&goog.inHtmlDocument_()&&goog.isDocumentLoading_()&&!k){goog.Dependency.defer_=!0;a.pause();var l=h.onreadystatechange;h.onreadystatechange=function(){"interactive"==h.readyState&&(h.onreadystatechange=
l,c(),a.resume());goog.isFunction(l)&&l.apply(void 0,arguments)}}else!goog.DebugLoader_.IS_OLD_IE_&&goog.inHtmlDocument_()&&goog.isDocumentLoading_()?d():c()}}},goog.TransformedDependency.prototype.transform=function(a){},goog.TranspiledDependency=function(a,b,c,d,e,f){goog.TransformedDependency.call(this,a,b,c,d,e);this.transpiler=f},goog.inherits(goog.TranspiledDependency,goog.TransformedDependency),goog.TranspiledDependency.prototype.transform=function(a){return this.transpiler.transpile(a,this.getPathName())},
goog.PreTranspiledEs6ModuleDependency=function(a,b,c,d,e){goog.TransformedDependency.call(this,a,b,c,d,e)},goog.inherits(goog.PreTranspiledEs6ModuleDependency,goog.TransformedDependency),goog.PreTranspiledEs6ModuleDependency.prototype.transform=function(a){return a},goog.GoogModuleDependency=function(a,b,c,d,e,f,g){goog.TransformedDependency.call(this,a,b,c,d,e);this.needsTranspile_=f;this.transpiler_=g},goog.inherits(goog.GoogModuleDependency,goog.TransformedDependency),goog.GoogModuleDependency.prototype.transform=
function(a){this.needsTranspile_&&(a=this.transpiler_.transpile(a,this.getPathName()));return goog.LOAD_MODULE_USING_EVAL&&void 0!==goog.global.JSON?"goog.loadModule("+goog.global.JSON.stringify(a+"\n//# sourceURL="+this.path+"\n")+");":'goog.loadModule(function(exports) {"use strict";'+a+"\n;return exports});\n//# sourceURL="+this.path+"\n"},goog.DebugLoader_.IS_OLD_IE_=!(goog.global.atob||!goog.global.document||!goog.global.document.all),goog.DebugLoader_.prototype.addDependency=function(a,b,c,
d){b=b||[];a=a.replace(/\\/g,"/");var e=goog.normalizePath_(goog.basePath+a);d&&"boolean"!==typeof d||(d=d?{module:goog.ModuleType.GOOG}:{});c=this.factory_.createDependency(e,a,b,c,d,goog.transpiler_.needsTranspile(d.lang||"es3",d.module));this.dependencies_[e]=c;for(c=0;c<b.length;c++)this.idToPath_[b[c]]=e;this.idToPath_[a]=e},goog.DependencyFactory=function(a){this.transpiler=a},goog.DependencyFactory.prototype.createDependency=function(a,b,c,d,e,f){return e.module==goog.ModuleType.GOOG?new goog.GoogModuleDependency(a,
b,c,d,e,f,this.transpiler):f?new goog.TranspiledDependency(a,b,c,d,e,this.transpiler):e.module==goog.ModuleType.ES6?"never"==goog.TRANSPILE&&goog.ASSUME_ES_MODULES_TRANSPILED?new goog.PreTranspiledEs6ModuleDependency(a,b,c,d,e):new goog.Es6ModuleDependency(a,b,c,d,e):new goog.Dependency(a,b,c,d,e)},goog.debugLoader_=new goog.DebugLoader_,goog.loadClosureDeps=function(){goog.debugLoader_.loadClosureDeps()},goog.setDependencyFactory=function(a){goog.debugLoader_.setDependencyFactory(a)},goog.TRUSTED_TYPES_POLICY_=
goog.TRUSTED_TYPES_POLICY_NAME?goog.createTrustedTypesPolicy(goog.TRUSTED_TYPES_POLICY_NAME+"#base"):null,goog.global.CLOSURE_NO_DEPS||goog.debugLoader_.loadClosureDeps(),goog.bootstrap=function(a,b){goog.debugLoader_.bootstrap(a,b)});goog.TRUSTED_TYPES_POLICY_NAME="goog";goog.identity_=function(a){return a};goog.createTrustedTypesPolicy=function(a){var b=null,c=goog.global.trustedTypes;if(!c||!c.createPolicy)return b;try{b=c.createPolicy(a,{createHTML:goog.identity_,createScript:goog.identity_,createScriptURL:goog.identity_})}catch(d){goog.logToConsole_(d.message)}return b};goog.debug={};goog.debug.Error=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,goog.debug.Error);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a));this.reportErrorToServer=!0};goog.inherits(goog.debug.Error,Error);goog.debug.Error.prototype.name="CustomError";goog.dom={};goog.dom.NodeType={ELEMENT:1,ATTRIBUTE:2,TEXT:3,CDATA_SECTION:4,ENTITY_REFERENCE:5,ENTITY:6,PROCESSING_INSTRUCTION:7,COMMENT:8,DOCUMENT:9,DOCUMENT_TYPE:10,DOCUMENT_FRAGMENT:11,NOTATION:12};goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){goog.debug.Error.call(this,goog.asserts.subs_(a,b));this.messagePattern=a};goog.inherits(goog.asserts.AssertionError,goog.debug.Error);goog.asserts.AssertionError.prototype.name="AssertionError";goog.asserts.DEFAULT_ERROR_HANDLER=function(a){throw a;};goog.asserts.errorHandler_=goog.asserts.DEFAULT_ERROR_HANDLER;
goog.asserts.subs_=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");return c+a[d]};goog.asserts.doAssertFailure_=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);a=new goog.asserts.AssertionError(""+e,f||[]);goog.asserts.errorHandler_(a)};goog.asserts.setErrorHandler=function(a){goog.asserts.ENABLE_ASSERTS&&(goog.asserts.errorHandler_=a)};
goog.asserts.assert=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!a&&goog.asserts.doAssertFailure_("",null,b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertExists=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&null==a&&goog.asserts.doAssertFailure_("Expected to exist: %s.",[a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.fail=function(a,b){goog.asserts.ENABLE_ASSERTS&&goog.asserts.errorHandler_(new goog.asserts.AssertionError("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};goog.asserts.assertNumber=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&"number"!==typeof a&&goog.asserts.doAssertFailure_("Expected number but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertString=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&"string"!==typeof a&&goog.asserts.doAssertFailure_("Expected string but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertFunction=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isFunction(a)&&goog.asserts.doAssertFailure_("Expected function but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertObject=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isObject(a)&&goog.asserts.doAssertFailure_("Expected object but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertArray=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!Array.isArray(a)&&goog.asserts.doAssertFailure_("Expected array but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertBoolean=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&"boolean"!==typeof a&&goog.asserts.doAssertFailure_("Expected boolean but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertElement=function(a,b,c){!goog.asserts.ENABLE_ASSERTS||goog.isObject(a)&&a.nodeType==goog.dom.NodeType.ELEMENT||goog.asserts.doAssertFailure_("Expected Element but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertInstanceof=function(a,b,c,d){!goog.asserts.ENABLE_ASSERTS||a instanceof b||goog.asserts.doAssertFailure_("Expected instanceof %s but got %s.",[goog.asserts.getType_(b),goog.asserts.getType_(a)],c,Array.prototype.slice.call(arguments,3));return a};goog.asserts.assertFinite=function(a,b,c){!goog.asserts.ENABLE_ASSERTS||"number"==typeof a&&isFinite(a)||goog.asserts.doAssertFailure_("Expected %s to be a finite number but it is not.",[a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertObjectPrototypeIsIntact=function(){for(var a in Object.prototype)goog.asserts.fail(a+" should not be enumerable in Object.prototype.")};goog.asserts.getType_=function(a){return a instanceof Function?a.displayName||a.name||"unknown type name":a instanceof Object?a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a):null===a?"null":typeof a};goog.array={};goog.NATIVE_ARRAY_PROTOTYPES=goog.TRUSTED_SITE;goog.array.ASSUME_NATIVE_FUNCTIONS=2012<goog.FEATURESET_YEAR;goog.array.peek=function(a){return a[a.length-1]};goog.array.last=goog.array.peek;
goog.array.indexOf=goog.NATIVE_ARRAY_PROTOTYPES&&(goog.array.ASSUME_NATIVE_FUNCTIONS||Array.prototype.indexOf)?function(a,b,c){goog.asserts.assert(null!=a.length);return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
goog.array.lastIndexOf=goog.NATIVE_ARRAY_PROTOTYPES&&(goog.array.ASSUME_NATIVE_FUNCTIONS||Array.prototype.lastIndexOf)?function(a,b,c){goog.asserts.assert(null!=a.length);return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
goog.array.forEach=goog.NATIVE_ARRAY_PROTOTYPES&&(goog.array.ASSUME_NATIVE_FUNCTIONS||Array.prototype.forEach)?function(a,b,c){goog.asserts.assert(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};goog.array.forEachRight=function(a,b,c){var d=a.length,e="string"===typeof a?a.split(""):a;for(--d;0<=d;--d)d in e&&b.call(c,e[d],d,a)};
goog.array.filter=goog.NATIVE_ARRAY_PROTOTYPES&&(goog.array.ASSUME_NATIVE_FUNCTIONS||Array.prototype.filter)?function(a,b,c){goog.asserts.assert(null!=a.length);return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g="string"===typeof a?a.split(""):a,k=0;k<d;k++)if(k in g){var h=g[k];b.call(c,h,k,a)&&(e[f++]=h)}return e};
goog.array.map=goog.NATIVE_ARRAY_PROTOTYPES&&(goog.array.ASSUME_NATIVE_FUNCTIONS||Array.prototype.map)?function(a,b,c){goog.asserts.assert(null!=a.length);return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
goog.array.reduce=goog.NATIVE_ARRAY_PROTOTYPES&&(goog.array.ASSUME_NATIVE_FUNCTIONS||Array.prototype.reduce)?function(a,b,c,d){goog.asserts.assert(null!=a.length);d&&(b=goog.bind(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;goog.array.forEach(a,function(c,g){e=b.call(d,e,c,g,a)});return e};
goog.array.reduceRight=goog.NATIVE_ARRAY_PROTOTYPES&&(goog.array.ASSUME_NATIVE_FUNCTIONS||Array.prototype.reduceRight)?function(a,b,c,d){goog.asserts.assert(null!=a.length);goog.asserts.assert(null!=b);d&&(b=goog.bind(b,d));return Array.prototype.reduceRight.call(a,b,c)}:function(a,b,c,d){var e=c;goog.array.forEachRight(a,function(c,g){e=b.call(d,e,c,g,a)});return e};
goog.array.some=goog.NATIVE_ARRAY_PROTOTYPES&&(goog.array.ASSUME_NATIVE_FUNCTIONS||Array.prototype.some)?function(a,b,c){goog.asserts.assert(null!=a.length);return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
goog.array.every=goog.NATIVE_ARRAY_PROTOTYPES&&(goog.array.ASSUME_NATIVE_FUNCTIONS||Array.prototype.every)?function(a,b,c){goog.asserts.assert(null!=a.length);return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};goog.array.count=function(a,b,c){var d=0;goog.array.forEach(a,function(a,f,g){b.call(c,a,f,g)&&++d},c);return d};
goog.array.find=function(a,b,c){b=goog.array.findIndex(a,b,c);return 0>b?null:"string"===typeof a?a.charAt(b):a[b]};goog.array.findIndex=function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};goog.array.findRight=function(a,b,c){b=goog.array.findIndexRight(a,b,c);return 0>b?null:"string"===typeof a?a.charAt(b):a[b]};
goog.array.findIndexRight=function(a,b,c){var d=a.length,e="string"===typeof a?a.split(""):a;for(--d;0<=d;d--)if(d in e&&b.call(c,e[d],d,a))return d;return-1};goog.array.contains=function(a,b){return 0<=goog.array.indexOf(a,b)};goog.array.isEmpty=function(a){return 0==a.length};goog.array.clear=function(a){if(!Array.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};goog.array.insert=function(a,b){goog.array.contains(a,b)||a.push(b)};
goog.array.insertAt=function(a,b,c){goog.array.splice(a,c,0,b)};goog.array.insertArrayAt=function(a,b,c){goog.partial(goog.array.splice,a,c,0).apply(null,b)};goog.array.insertBefore=function(a,b,c){var d;2==arguments.length||0>(d=goog.array.indexOf(a,c))?a.push(b):goog.array.insertAt(a,b,d)};goog.array.remove=function(a,b){b=goog.array.indexOf(a,b);var c;(c=0<=b)&&goog.array.removeAt(a,b);return c};
goog.array.removeLast=function(a,b){b=goog.array.lastIndexOf(a,b);return 0<=b?(goog.array.removeAt(a,b),!0):!1};goog.array.removeAt=function(a,b){goog.asserts.assert(null!=a.length);return 1==Array.prototype.splice.call(a,b,1).length};goog.array.removeIf=function(a,b,c){b=goog.array.findIndex(a,b,c);return 0<=b?(goog.array.removeAt(a,b),!0):!1};goog.array.removeAllIf=function(a,b,c){var d=0;goog.array.forEachRight(a,function(e,f){b.call(c,e,f,a)&&goog.array.removeAt(a,f)&&d++});return d};
goog.array.concat=function(a){return Array.prototype.concat.apply([],arguments)};goog.array.join=function(a){return Array.prototype.concat.apply([],arguments)};goog.array.toArray=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};goog.array.clone=goog.array.toArray;goog.array.extend=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(goog.isArrayLike(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};
goog.array.splice=function(a,b,c,d){goog.asserts.assert(null!=a.length);return Array.prototype.splice.apply(a,goog.array.slice(arguments,1))};goog.array.slice=function(a,b,c){goog.asserts.assert(null!=a.length);return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};
goog.array.removeDuplicates=function(a,b,c){b=b||a;var d=function(a){return goog.isObject(a)?"o"+goog.getUid(a):(typeof a).charAt(0)+a};c=c||d;d={};for(var e=0,f=0;f<a.length;){var g=a[f++],k=c(g);Object.prototype.hasOwnProperty.call(d,k)||(d[k]=!0,b[e++]=g)}b.length=e};goog.array.binarySearch=function(a,b,c){return goog.array.binarySearch_(a,c||goog.array.defaultCompare,!1,b)};goog.array.binarySelect=function(a,b,c){return goog.array.binarySearch_(a,b,!0,void 0,c)};
goog.array.binarySearch_=function(a,b,c,d,e){for(var f=0,g=a.length,k;f<g;){var h=f+(g-f>>>1);var l=c?b.call(e,a[h],h,a):b(d,a[h]);0<l?f=h+1:(g=h,k=!l)}return k?f:-f-1};goog.array.sort=function(a,b){a.sort(b||goog.array.defaultCompare)};goog.array.stableSort=function(a,b){for(var c=Array(a.length),d=0;d<a.length;d++)c[d]={index:d,value:a[d]};var e=b||goog.array.defaultCompare;goog.array.sort(c,function(a,b){return e(a.value,b.value)||a.index-b.index});for(d=0;d<a.length;d++)a[d]=c[d].value};
goog.array.sortByKey=function(a,b,c){var d=c||goog.array.defaultCompare;goog.array.sort(a,function(a,c){return d(b(a),b(c))})};goog.array.sortObjectsByKey=function(a,b,c){goog.array.sortByKey(a,function(a){return a[b]},c)};goog.array.isSorted=function(a,b,c){b=b||goog.array.defaultCompare;for(var d=1;d<a.length;d++){var e=b(a[d-1],a[d]);if(0<e||0==e&&c)return!1}return!0};
goog.array.equals=function(a,b,c){if(!goog.isArrayLike(a)||!goog.isArrayLike(b)||a.length!=b.length)return!1;var d=a.length;c=c||goog.array.defaultCompareEquality;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return!1;return!0};goog.array.compare3=function(a,b,c){c=c||goog.array.defaultCompare;for(var d=Math.min(a.length,b.length),e=0;e<d;e++){var f=c(a[e],b[e]);if(0!=f)return f}return goog.array.defaultCompare(a.length,b.length)};goog.array.defaultCompare=function(a,b){return a>b?1:a<b?-1:0};
goog.array.inverseDefaultCompare=function(a,b){return-goog.array.defaultCompare(a,b)};goog.array.defaultCompareEquality=function(a,b){return a===b};goog.array.binaryInsert=function(a,b,c){c=goog.array.binarySearch(a,b,c);return 0>c?(goog.array.insertAt(a,b,-(c+1)),!0):!1};goog.array.binaryRemove=function(a,b,c){b=goog.array.binarySearch(a,b,c);return 0<=b?goog.array.removeAt(a,b):!1};
goog.array.bucket=function(a,b,c){for(var d={},e=0;e<a.length;e++){var f=a[e],g=b.call(c,f,e,a);void 0!==g&&(d[g]||(d[g]=[])).push(f)}return d};goog.array.toObject=function(a,b,c){var d={};goog.array.forEach(a,function(e,f){d[b.call(c,e,f,a)]=e});return d};goog.array.range=function(a,b,c){var d=[],e=0,f=a;c=c||1;void 0!==b&&(e=a,f=b);if(0>c*(f-e))return[];if(0<c)for(a=e;a<f;a+=c)d.push(a);else for(a=e;a>f;a+=c)d.push(a);return d};goog.array.repeat=function(a,b){for(var c=[],d=0;d<b;d++)c[d]=a;return c};
goog.array.flatten=function(a){for(var b=[],c=0;c<arguments.length;c++){var d=arguments[c];if(Array.isArray(d))for(var e=0;e<d.length;e+=8192){var f=goog.array.slice(d,e,e+8192);f=goog.array.flatten.apply(null,f);for(var g=0;g<f.length;g++)b.push(f[g])}else b.push(d)}return b};goog.array.rotate=function(a,b){goog.asserts.assert(null!=a.length);a.length&&(b%=a.length,0<b?Array.prototype.unshift.apply(a,a.splice(-b,b)):0>b&&Array.prototype.push.apply(a,a.splice(0,-b)));return a};
goog.array.moveItem=function(a,b,c){goog.asserts.assert(0<=b&&b<a.length);goog.asserts.assert(0<=c&&c<a.length);b=Array.prototype.splice.call(a,b,1);Array.prototype.splice.call(a,c,0,b[0])};goog.array.zip=function(a){if(!arguments.length)return[];for(var b=[],c=arguments[0].length,d=1;d<arguments.length;d++)arguments[d].length<c&&(c=arguments[d].length);for(d=0;d<c;d++){for(var e=[],f=0;f<arguments.length;f++)e.push(arguments[f][d]);b.push(e)}return b};
goog.array.shuffle=function(a,b){b=b||Math.random;for(var c=a.length-1;0<c;c--){var d=Math.floor(b()*(c+1)),e=a[c];a[c]=a[d];a[d]=e}};goog.array.copyByIndex=function(a,b){var c=[];goog.array.forEach(b,function(b){c.push(a[b])});return c};goog.array.concatMap=function(a,b,c){return goog.array.concat.apply([],goog.array.map(a,b,c))};/*
 DEDUPE_ON_MINIFY
 Copyright 2015 The AMP HTML Authors. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS-IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the license.
*/
var module$exports$amp$htmlparser$interface={toLowerCase:function(a){var b=a.toLowerCase();return b.length==a.length?b:a.replace(/[A-Z]/g,function(a){return String.fromCharCode(a.charCodeAt(0)|32)})},toUpperCase:function(a){var b=a.toUpperCase();return b.length==a.length?b:a.replace(/[a-z]/g,function(a){return String.fromCharCode(a.charCodeAt(0)&223)})},ParsedAttr:function(){this.value=this.name=""},ParsedHtmlTag:function(a,b){b=b||[];this.tagName_=(0,module$exports$amp$htmlparser$interface.toUpperCase)(a);
this.attrs_=[];for(a=0;a<b.length;a+=2){var c=new module$exports$amp$htmlparser$interface.ParsedAttr;c.name=(0,module$exports$amp$htmlparser$interface.toLowerCase)(b[a]);c.value=b[a+1];c.name===c.value&&(c.value="");this.attrs_.push(c)}goog.array.sort(this.attrs_,function(a,b){return a.name>b.name?1:a.name<b.name?-1:0});this.attrsByKey_=null}};module$exports$amp$htmlparser$interface.ParsedHtmlTag.prototype.lowerName=function(){return(0,module$exports$amp$htmlparser$interface.toLowerCase)(this.tagName_)};
module$exports$amp$htmlparser$interface.ParsedHtmlTag.prototype.upperName=function(){return this.tagName_};module$exports$amp$htmlparser$interface.ParsedHtmlTag.prototype.attrs=function(){return this.attrs_};module$exports$amp$htmlparser$interface.ParsedHtmlTag.prototype.attrsByKey=function(){if(null===this.attrsByKey_){this.attrsByKey_=Object.create(null);for(var a=$jscomp.makeIterator(this.attrs()),b=a.next();!b.done;b=a.next())b=b.value,this.attrsByKey_[b.name]=b.value}return this.attrsByKey_};
module$exports$amp$htmlparser$interface.ParsedHtmlTag.prototype.hasDuplicateAttrs=function(){for(var a="",b="",c=$jscomp.makeIterator(this.attrs()),d=c.next();!d.done;d=c.next()){d=d.value;if(a===d.name&&b!==d.value)return d.name;a=d.name;b=d.value}return null};module$exports$amp$htmlparser$interface.ParsedHtmlTag.prototype.dedupeAttrs=function(){for(var a=[],b="",c=$jscomp.makeIterator(this.attrs_),d=c.next();!d.done;d=c.next())d=d.value,b!==d.name&&a.push(d),b=d.name;this.attrs_=a};
module$exports$amp$htmlparser$interface.ParsedHtmlTag.prototype.isEmpty=function(){return 0===this.tagName_.length};module$exports$amp$htmlparser$interface.HtmlSaxHandler=function(){};module$exports$amp$htmlparser$interface.HtmlSaxHandler.prototype.startTag=function(a){};module$exports$amp$htmlparser$interface.HtmlSaxHandler.prototype.endTag=function(a){};module$exports$amp$htmlparser$interface.HtmlSaxHandler.prototype.pcdata=function(a){};
module$exports$amp$htmlparser$interface.HtmlSaxHandler.prototype.rcdata=function(a){};module$exports$amp$htmlparser$interface.HtmlSaxHandler.prototype.cdata=function(a){};module$exports$amp$htmlparser$interface.HtmlSaxHandler.prototype.startDoc=function(){};module$exports$amp$htmlparser$interface.HtmlSaxHandler.prototype.endDoc=function(){};module$exports$amp$htmlparser$interface.HtmlSaxHandler.prototype.markManufacturedBody=function(){};
module$exports$amp$htmlparser$interface.HtmlSaxHandler.prototype.effectiveBodyTag=function(a){};module$exports$amp$htmlparser$interface.DocLocator=function(){};module$exports$amp$htmlparser$interface.DocLocator.prototype.getLine=function(){};module$exports$amp$htmlparser$interface.DocLocator.prototype.getCol=function(){};module$exports$amp$htmlparser$interface.HtmlSaxHandlerWithLocation=function(){module$exports$amp$htmlparser$interface.HtmlSaxHandler.call(this)};
$jscomp.inherits(module$exports$amp$htmlparser$interface.HtmlSaxHandlerWithLocation,module$exports$amp$htmlparser$interface.HtmlSaxHandler);module$exports$amp$htmlparser$interface.HtmlSaxHandlerWithLocation.prototype.setDocLocator=function(a){};/*

 Copyright 2015 The AMP HTML Authors. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS-IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the license.

 Credits:
   Copyright 2006-2008, The Google Caja project, licensed under the
   Apache License (http://code.google.com/p/google-caja/).
   Copyright 2009, The Closure Library Authors, licensed under the
   Apache License.
*/
var module$exports$amp$htmlparser={},module$contents$amp$htmlparser_ElementsWithNoEndElements={BASE:0,LINK:0,META:0,HR:0,BR:0,WBR:0,IMG:0,EMBED:0,PARAM:0,SOURCE:0,TRACK:0,AREA:0,COL:0,INPUT:0,KEYGEN:0},module$contents$amp$htmlparser_HtmlStructureElements={"!DOCTYPE":0,HTML:0,HEAD:0,BODY:0},module$contents$amp$htmlparser_HeadElements={HEAD:0,TITLE:0,BASE:0,LINK:0,META:0,STYLE:0,NOSCRIPT:0,SCRIPT:0},module$contents$amp$htmlparser_ElementsWhichClosePTag={ADDRESS:0,ARTICLE:0,ASIDE:0,BLOCKQUOTE:0,DIR:0,
DL:0,FIELDSET:0,FOOTER:0,FORM:0,H1:0,H2:0,H3:0,H4:0,H5:0,H6:0,HEADER:0,HR:0,MENU:0,NAV:0,OL:0,P:0,PRE:0,SECTION:0,TABLE:0,UL:0},module$contents$amp$htmlparser_TagRegion={PRE_DOCTYPE:0,PRE_HTML:1,PRE_HEAD:2,IN_HEAD:3,PRE_BODY:4,IN_BODY:5,IN_SVG:6},module$contents$amp$htmlparser_TagNameStack=function(a){this.stack_=[];this.handler_=a;this.region_=module$contents$amp$htmlparser_TagRegion.PRE_DOCTYPE;this.isBodyStarted_=this.isHeadStarted_=!1;this.effectiveBodyAttribs_=[]};
module$contents$amp$htmlparser_TagNameStack.prototype.effectiveBodyAttribs=function(){return this.effectiveBodyAttribs_};
module$contents$amp$htmlparser_TagNameStack.prototype.startTag=function(a){"BODY"===a.upperName()&&(this.effectiveBodyAttribs_=this.effectiveBodyAttribs_.concat(a.attrs().slice()));switch(this.region_){case module$contents$amp$htmlparser_TagRegion.PRE_DOCTYPE:"!DOCTYPE"===a.upperName()?this.region_=module$contents$amp$htmlparser_TagRegion.PRE_HTML:"HTML"===a.upperName()?this.region_=module$contents$amp$htmlparser_TagRegion.PRE_HEAD:"HEAD"===a.upperName()?this.region_=module$contents$amp$htmlparser_TagRegion.IN_HEAD:
"BODY"===a.upperName()?this.region_=module$contents$amp$htmlparser_TagRegion.IN_BODY:module$contents$amp$htmlparser_HtmlStructureElements.hasOwnProperty(a.upperName())||(module$contents$amp$htmlparser_HeadElements.hasOwnProperty(a.upperName())?this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("HEAD")):(this.handler_.markManufacturedBody&&this.handler_.markManufacturedBody(),this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("BODY"))));break;case module$contents$amp$htmlparser_TagRegion.PRE_HTML:if("!DOCTYPE"===
a.upperName())return;"HTML"===a.upperName()?this.region_=module$contents$amp$htmlparser_TagRegion.PRE_HEAD:"HEAD"===a.upperName()?this.region_=module$contents$amp$htmlparser_TagRegion.IN_HEAD:"BODY"===a.upperName()?this.region_=module$contents$amp$htmlparser_TagRegion.IN_BODY:module$contents$amp$htmlparser_HtmlStructureElements.hasOwnProperty(a.upperName())||(module$contents$amp$htmlparser_HeadElements.hasOwnProperty(a.upperName())?this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("HEAD")):
(this.handler_.markManufacturedBody&&this.handler_.markManufacturedBody(),this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("BODY"))));break;case module$contents$amp$htmlparser_TagRegion.PRE_HEAD:if("!DOCTYPE"===a.upperName()||"HTML"===a.upperName())return;"HEAD"===a.upperName()?this.region_=module$contents$amp$htmlparser_TagRegion.IN_HEAD:"BODY"===a.upperName()?this.region_=module$contents$amp$htmlparser_TagRegion.IN_BODY:module$contents$amp$htmlparser_HtmlStructureElements.hasOwnProperty(a.upperName())||
(module$contents$amp$htmlparser_HeadElements.hasOwnProperty(a.upperName())?this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("HEAD")):(this.handler_.markManufacturedBody&&this.handler_.markManufacturedBody(),this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("BODY"))));break;case module$contents$amp$htmlparser_TagRegion.IN_HEAD:if("!DOCTYPE"===a.upperName()||"HTML"===a.upperName()||"HEAD"===a.upperName())return;module$contents$amp$htmlparser_HeadElements.hasOwnProperty(a.upperName())||
(this.endTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("HEAD")),"BODY"!==a.upperName()?(this.handler_.markManufacturedBody&&this.handler_.markManufacturedBody(),this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("BODY"))):this.region_=module$contents$amp$htmlparser_TagRegion.IN_BODY);break;case module$contents$amp$htmlparser_TagRegion.PRE_BODY:if("!DOCTYPE"===a.upperName()||"HTML"===a.upperName()||"HEAD"===a.upperName())return;"BODY"!==a.upperName()?(this.handler_.markManufacturedBody&&
this.handler_.markManufacturedBody(),this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("BODY"))):this.region_=module$contents$amp$htmlparser_TagRegion.IN_BODY;break;case module$contents$amp$htmlparser_TagRegion.IN_BODY:if("!DOCTYPE"===a.upperName()||"HTML"===a.upperName()||"HEAD"===a.upperName()||"BODY"===a.upperName())return;if("SVG"===a.upperName()){this.region_=module$contents$amp$htmlparser_TagRegion.IN_SVG;break}if(0<this.stack_.length){var b=this.stack_[this.stack_.length-
1];"P"===b&&module$contents$amp$htmlparser_ElementsWhichClosePTag.hasOwnProperty(a.upperName())?this.endTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("P")):"DD"!=a.upperName()&&"DT"!=a.upperName()||"DD"!=b&&"DT"!=b?"LI"==a.upperName()&&"LI"==b&&this.endTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("LI")):this.endTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag(b))}break;case module$contents$amp$htmlparser_TagRegion.IN_SVG:this.handler_.startTag&&this.handler_.startTag(a);
this.stack_.push(a.upperName());return}this.handler_.startTag&&this.handler_.startTag(a);module$contents$amp$htmlparser_ElementsWithNoEndElements.hasOwnProperty(a.upperName())?this.handler_.endTag&&this.handler_.endTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag(a.upperName())):this.stack_.push(a.upperName())};
module$contents$amp$htmlparser_TagNameStack.prototype.pcdata=function(a){if(!module$contents$amp$htmlparser_SPACE_RE_.test(a))if(module$contents$amp$htmlparser_CPP_SPACE_RE_.test(a))switch(this.region_){case module$contents$amp$htmlparser_TagRegion.PRE_DOCTYPE:case module$contents$amp$htmlparser_TagRegion.PRE_HTML:case module$contents$amp$htmlparser_TagRegion.PRE_HEAD:case module$contents$amp$htmlparser_TagRegion.IN_HEAD:case module$contents$amp$htmlparser_TagRegion.PRE_BODY:this.handler_.markManufacturedBody&&this.handler_.markManufacturedBody()}else switch(this.region_){case module$contents$amp$htmlparser_TagRegion.PRE_DOCTYPE:case module$contents$amp$htmlparser_TagRegion.PRE_HTML:this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("HTML"));
case module$contents$amp$htmlparser_TagRegion.PRE_HEAD:this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("HEAD"));case module$contents$amp$htmlparser_TagRegion.IN_HEAD:this.endTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("HEAD"));case module$contents$amp$htmlparser_TagRegion.PRE_BODY:this.handler_.markManufacturedBody&&this.handler_.markManufacturedBody(),this.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag("BODY"))}this.handler_.pcdata(a)};
module$contents$amp$htmlparser_TagNameStack.prototype.endTag=function(a){this.region_==module$contents$amp$htmlparser_TagRegion.IN_HEAD&&"HEAD"===a.upperName()&&(this.region_=module$contents$amp$htmlparser_TagRegion.PRE_BODY);if("BODY"!==a.upperName())for(var b=this.stack_.length-1;0<=b;b--)if(this.stack_[b]===a.upperName()){for(;this.stack_.length>b;)"SVG"===this.stack_[this.stack_.length-1]&&(this.region_=module$contents$amp$htmlparser_TagRegion.IN_BODY),this.handler_.endTag&&this.handler_.endTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag(this.stack_.pop()));
break}};module$contents$amp$htmlparser_TagNameStack.prototype.exitRemainingTags=function(){for(;0<this.stack_.length;)this.handler_.endTag&&this.handler_.endTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag(this.stack_.pop()))};module$exports$amp$htmlparser.HtmlParser=function(){};
module$exports$amp$htmlparser.HtmlParser.prototype.parse=function(a,b){var c=null,d=!1,e=[],f,g,k=new module$contents$amp$htmlparser_TagNameStack(a),h=null;a instanceof module$exports$amp$htmlparser$interface.HtmlSaxHandlerWithLocation&&(h=new module$contents$amp$htmlparser_DocLocatorImpl(b),a.setDocLocator(h));for(a.startDoc();b;){var l=b.match(d?module$contents$amp$htmlparser_INSIDE_TAG_TOKEN_:module$contents$amp$htmlparser_OUTSIDE_TAG_TOKEN_);h&&h.advancePos(l[0]);b=b.substring(l[0].length);if(d)if(l[1]){var p=
(0,module$exports$amp$htmlparser$interface.toLowerCase)(l[1]),n="";if(l[2]){l=l[3];switch(l.charCodeAt(0)){case 34:case 39:l=l.substring(1,l.length-1)}n=this.unescapeEntities_(this.stripNULs_(l))}e.push(p,n)}else{if(l[4]){void 0!==f&&(g?k.startTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag(m,e)):k.endTag(new module$exports$amp$htmlparser$interface.ParsedHtmlTag(m)));g&&f&(module$exports$amp$htmlparser.EFlags.CDATA|module$exports$amp$htmlparser.EFlags.RCDATA)&&(c=null===c?(0,module$exports$amp$htmlparser$interface.toUpperCase)(b):
c.substring(c.length-b.length),d=c.indexOf("</"+m),0>d&&(d=b.length),f&module$exports$amp$htmlparser.EFlags.CDATA?a.cdata&&a.cdata(b.substring(0,d)):a.rcdata&&a.rcdata(this.normalizeRCData_(b.substring(0,d))),h&&h.advancePos(b.substring(0,d)),b=b.substring(d));var m=f=g=void 0;e.length=0;h&&h.snapshotPos();d=!1}}else if(l[1])k.pcdata(l[0]);else if(l[3])g=!l[2],h&&h.snapshotPos(),d=!0,m=(0,module$exports$amp$htmlparser$interface.toUpperCase)(l[3]),f=module$exports$amp$htmlparser.Elements.hasOwnProperty(m)?
module$exports$amp$htmlparser.Elements[m]:module$exports$amp$htmlparser.EFlags.UNKNOWN_OR_CUSTOM;else if(l[4])h&&h.snapshotPos(),k.pcdata(l[4]);else if(l[5])switch(l[5]){case "<":k.pcdata("&lt;");break;case ">":k.pcdata("&gt;");break;default:k.pcdata("&amp;")}}!d&&h&&h.snapshotPos();k.exitRemainingTags();a.effectiveBodyTag(k.effectiveBodyAttribs());a.endDoc()};
module$exports$amp$htmlparser.HtmlParser.prototype.lookupEntity_=function(a){a=(0,module$exports$amp$htmlparser$interface.toLowerCase)(a.substring(1,a.length-1));if(module$exports$amp$htmlparser.Entities.hasOwnProperty(a))return module$exports$amp$htmlparser.Entities[a];var b=a.match(module$contents$amp$htmlparser_DECIMAL_ESCAPE_RE_);return b?String.fromCharCode(parseInt(b[1],10)):(b=a.match(module$contents$amp$htmlparser_HEX_ESCAPE_RE_))?String.fromCharCode(parseInt(b[1],16)):a};
module$exports$amp$htmlparser.HtmlParser.prototype.stripNULs_=function(a){return a.replace(module$contents$amp$htmlparser_NULL_RE_,"")};module$exports$amp$htmlparser.HtmlParser.prototype.unescapeEntities_=function(a){return a.replace(module$contents$amp$htmlparser_ENTITY_RE_,goog.bind(this.lookupEntity_,this))};
module$exports$amp$htmlparser.HtmlParser.prototype.normalizeRCData_=function(a){return a.replace(module$contents$amp$htmlparser_LOOSE_AMP_RE_,"&amp;$1").replace(module$contents$amp$htmlparser_LT_RE,"&lt;").replace(module$contents$amp$htmlparser_GT_RE,"&gt;")};module$exports$amp$htmlparser.Entities={colon:":",lt:"<",gt:">",amp:"&",nbsp:"\u00a0",quot:'"',apos:"'"};module$exports$amp$htmlparser.EFlags={OPTIONAL_ENDTAG:1,EMPTY:2,CDATA:4,RCDATA:8,UNSAFE:16,FOLDABLE:32,UNKNOWN_OR_CUSTOM:64};
module$exports$amp$htmlparser.Elements={A:0,ABBR:0,ACRONYM:0,ADDRESS:0,APPLET:module$exports$amp$htmlparser.EFlags.UNSAFE,AREA:module$exports$amp$htmlparser.EFlags.EMPTY,B:0,BASE:module$exports$amp$htmlparser.EFlags.EMPTY|module$exports$amp$htmlparser.EFlags.UNSAFE,BASEFONT:module$exports$amp$htmlparser.EFlags.EMPTY|module$exports$amp$htmlparser.EFlags.UNSAFE,BDO:0,BIG:0,BLOCKQUOTE:0,BODY:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG|module$exports$amp$htmlparser.EFlags.UNSAFE|module$exports$amp$htmlparser.EFlags.FOLDABLE,
BR:module$exports$amp$htmlparser.EFlags.EMPTY,BUTTON:0,CANVAS:0,CAPTION:0,CENTER:0,CITE:0,CODE:0,COL:module$exports$amp$htmlparser.EFlags.EMPTY,COLGROUP:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,DD:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,DEL:0,DFN:0,DIR:0,DIV:0,DL:0,DT:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,EM:0,FIELDSET:0,FONT:0,FORM:0,FRAME:module$exports$amp$htmlparser.EFlags.EMPTY|module$exports$amp$htmlparser.EFlags.UNSAFE,FRAMESET:module$exports$amp$htmlparser.EFlags.UNSAFE,
H1:0,H2:0,H3:0,H4:0,H5:0,H6:0,HEAD:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG|module$exports$amp$htmlparser.EFlags.UNSAFE|module$exports$amp$htmlparser.EFlags.FOLDABLE,HR:module$exports$amp$htmlparser.EFlags.EMPTY,HTML:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG|module$exports$amp$htmlparser.EFlags.UNSAFE|module$exports$amp$htmlparser.EFlags.FOLDABLE,I:0,IFRAME:module$exports$amp$htmlparser.EFlags.UNSAFE|module$exports$amp$htmlparser.EFlags.CDATA,IMG:module$exports$amp$htmlparser.EFlags.EMPTY,
INPUT:module$exports$amp$htmlparser.EFlags.EMPTY,INS:0,ISINDEX:module$exports$amp$htmlparser.EFlags.EMPTY|module$exports$amp$htmlparser.EFlags.UNSAFE,KBD:0,LABEL:0,LEGEND:0,LI:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,LINK:module$exports$amp$htmlparser.EFlags.EMPTY|module$exports$amp$htmlparser.EFlags.UNSAFE,MAP:0,MENU:0,META:module$exports$amp$htmlparser.EFlags.EMPTY|module$exports$amp$htmlparser.EFlags.UNSAFE,NOFRAMES:module$exports$amp$htmlparser.EFlags.UNSAFE|module$exports$amp$htmlparser.EFlags.CDATA,
NOSCRIPT:module$exports$amp$htmlparser.EFlags.UNSAFE,OBJECT:module$exports$amp$htmlparser.EFlags.UNSAFE,OL:0,OPTGROUP:0,OPTION:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,P:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,PARAM:module$exports$amp$htmlparser.EFlags.EMPTY|module$exports$amp$htmlparser.EFlags.UNSAFE,PRE:0,Q:0,S:0,SAMP:0,SCRIPT:module$exports$amp$htmlparser.EFlags.UNSAFE|module$exports$amp$htmlparser.EFlags.CDATA,SELECT:0,SMALL:0,SPAN:0,STRIKE:0,STRONG:0,STYLE:module$exports$amp$htmlparser.EFlags.UNSAFE|
module$exports$amp$htmlparser.EFlags.CDATA,SUB:0,SUP:0,TABLE:0,TBODY:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,TD:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,TEXTAREA:module$exports$amp$htmlparser.EFlags.RCDATA,TFOOT:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,TH:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,THEAD:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,TITLE:module$exports$amp$htmlparser.EFlags.RCDATA|module$exports$amp$htmlparser.EFlags.UNSAFE,TR:module$exports$amp$htmlparser.EFlags.OPTIONAL_ENDTAG,
TT:0,U:0,UL:0,VAR:0};
var module$contents$amp$htmlparser_LOOSE_AMP_RE_=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,module$contents$amp$htmlparser_LT_RE=/</g,module$contents$amp$htmlparser_GT_RE=/>/g,module$contents$amp$htmlparser_NULL_RE_=/\0/g,module$contents$amp$htmlparser_ENTITY_RE_=/&(#\d+|#x[0-9A-Fa-f]+|\w+);/g,module$contents$amp$htmlparser_SPACE_RE_=/^[ \f\n\r\t]*$/,module$contents$amp$htmlparser_CPP_SPACE_RE_=/^[ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]*$/,module$contents$amp$htmlparser_DECIMAL_ESCAPE_RE_=/^#(\d+)$/,
module$contents$amp$htmlparser_HEX_ESCAPE_RE_=/^#x([0-9A-Fa-f]+)$/,module$contents$amp$htmlparser_INSIDE_TAG_TOKEN_=/^[ \t\n\f\r\v]*(?:(?:([^\t\r\n /=>][^\t\r\n =>]*|[^\t\r\n =>]+[^ >]|\/+(?!>))(\s*=\s*("[^"]*"|'[^']*'|(?=[a-z][a-z-]*\s+=)|[^>\s]*))?)|(\/?>)|[^a-z\s>]+)/i,module$contents$amp$htmlparser_OUTSIDE_TAG_TOKEN_=/^(?:&(\#[0-9]+|\#[x][0-9a-f]+|\w+);|<[!]--[\s\S]*?(?:--[!]?>|$)|<(\/)?([a-z!\?][^\0 \n\r\t\f\v>/]*)|([^<&>]+)|([<&>]))/i,module$contents$amp$htmlparser_DocLocatorImpl=function(a){module$exports$amp$htmlparser$interface.DocLocator.call(this);
this.lineByPos_=[];this.colByPos_=[];for(var b=1,c=0,d=0;d<a.length;++d)this.lineByPos_[d]=b,this.colByPos_[d]=c,"\n"==a.charAt(d)?(++b,c=0):++c;this.previousPos_=this.pos_=0;this.line_=1;this.col_=0};$jscomp.inherits(module$contents$amp$htmlparser_DocLocatorImpl,module$exports$amp$htmlparser$interface.DocLocator);module$contents$amp$htmlparser_DocLocatorImpl.prototype.advancePos=function(a){this.previousPos_=this.pos_;this.pos_+=a.length};
module$contents$amp$htmlparser_DocLocatorImpl.prototype.snapshotPos=function(){this.previousPos_<this.lineByPos_.length&&(this.line_=this.lineByPos_[this.previousPos_],this.col_=this.colByPos_[this.previousPos_])};module$contents$amp$htmlparser_DocLocatorImpl.prototype.getLine=function(){return this.line_};module$contents$amp$htmlparser_DocLocatorImpl.prototype.getCol=function(){return this.col_};
function module$contents$amp$htmlparser_unusedHtmlParser(){console.log(module$contents$amp$htmlparser_ElementsWithNoEndElements[""]);console.log(module$contents$amp$htmlparser_HtmlStructureElements[""]);console.log(module$contents$amp$htmlparser_HeadElements[""]);console.log(module$contents$amp$htmlparser_ElementsWhichClosePTag[""])};var module$exports$amp$htmlparser$HtmlParserTest={},module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler=function(){module$exports$amp$htmlparser$interface.HtmlSaxHandler.call(this);this.log=[]};$jscomp.inherits(module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler,module$exports$amp$htmlparser$interface.HtmlSaxHandler);module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.startDoc=function(){this.log.push("startDoc()")};
module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.cdata=function(a){this.log.push('cdata("'+a+'")')};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.pcdata=function(a){this.log.push('pcdata("'+a+'")')};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.rcdata=function(a){this.log.push('rcdata("'+a+'")')};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.endDoc=function(){this.log.push("endDoc()")};
module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.markManufacturedBody=function(){this.log.push("markManufacturedBody()")};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.startTag=function(a){a.dedupeAttrs();this.log.push("startTag("+a.upperName()+","+this.attrsToString(a.attrs())+")")};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.endTag=function(a){this.log.push("endTag("+a.upperName()+")")};
module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.effectiveBodyTag=function(a){this.log.push("effectiveBodyTag("+this.attrsToString(a)+")")};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler.prototype.attrsToString=function(a){var b="[",c=!0;a=$jscomp.makeIterator(a);for(var d=a.next();!d.done;d=a.next())d=d.value,c?c=!1:b+=",",b+=d.name+","+d.value;return b+"]"};
describe("HtmlParser",function(){it("parses basic text",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"hello world");expect(a.log).toEqual('startDoc();startTag(HTML,[]);startTag(HEAD,[]);endTag(HEAD);markManufacturedBody();startTag(BODY,[]);pcdata("hello world");endTag(BODY);endTag(HTML);effectiveBodyTag([]);endDoc()'.split(";"))});it("parses image tag",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;
(new module$exports$amp$htmlparser.HtmlParser).parse(a,'<img src="hello.gif">');expect(a.log).toEqual("startDoc() markManufacturedBody() startTag(BODY,[]) startTag(IMG,[src,hello.gif]) endTag(IMG) endTag(BODY) effectiveBodyTag([]) endDoc()".split(" "))});it("parses tags inside tags",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<div><span>hello world</span></div>");expect(a.log).toEqual('startDoc();markManufacturedBody();startTag(BODY,[]);startTag(DIV,[]);startTag(SPAN,[]);pcdata("hello world");endTag(SPAN);endTag(DIV);endTag(BODY);effectiveBodyTag([]);endDoc()'.split(";"))});
it("parses tag with multiple attrs",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,'<img src="hello.gif" width="400px">');expect(a.log).toEqual("startDoc() markManufacturedBody() startTag(BODY,[]) startTag(IMG,[src,hello.gif,width,400px]) endTag(IMG) endTag(BODY) effectiveBodyTag([]) endDoc()".split(" "))});it("parses tag with duplicate attrs",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;
(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<a class=foo class=bar>");expect(a.log).toEqual("startDoc() markManufacturedBody() startTag(BODY,[]) startTag(A,[class,foo]) endTag(A) endTag(BODY) effectiveBodyTag([]) endDoc()".split(" "))});it("parses tag with boolean attr",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<input type=checkbox checked>");expect(a.log).toEqual("startDoc() markManufacturedBody() startTag(BODY,[]) startTag(INPUT,[checked,,type,checkbox]) endTag(INPUT) endTag(BODY) effectiveBodyTag([]) endDoc()".split(" "))});
it("parses unclosed tag",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<span>");expect(a.log).toEqual("startDoc() markManufacturedBody() startTag(BODY,[]) startTag(SPAN,[]) endTag(SPAN) endTag(BODY) effectiveBodyTag([]) endDoc()".split(" "))});it("parses style tag",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,'<span style="background-color: black;"></span>');
expect(a.log).toEqual("startDoc(){markManufacturedBody(){startTag(BODY,[]){startTag(SPAN,[style,background-color: black;]){endTag(SPAN){endTag(BODY){effectiveBodyTag([]){endDoc()".split("{"))});it("parses cdata",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,'<script><![CDATA[alert("hey");]]\x3e\x3c/script>');expect(a.log).toEqual('startDoc() startTag(HEAD,[]) startTag(SCRIPT,[]) cdata("<![CDATA[alert("hey");]]\x3e") endTag(SCRIPT) endTag(HEAD) effectiveBodyTag([]) endDoc()'.split(" "))});
it("parses several tags on the same level",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<img><p>hello<img><div/></p>");expect(a.log).toEqual('startDoc() markManufacturedBody() startTag(BODY,[]) startTag(IMG,[]) endTag(IMG) startTag(P,[]) pcdata("hello") startTag(IMG,[]) endTag(IMG) startTag(DIV,[]) endTag(DIV) endTag(P) endTag(BODY) effectiveBodyTag([]) endDoc()'.split(" "))});it("will not hold state between two parse calls",
function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler,b=new module$exports$amp$htmlparser.HtmlParser;b.parse(a,"<div/>");b.parse(a,"<div/>");expect(a.log).toEqual("startDoc() markManufacturedBody() startTag(BODY,[]) startTag(DIV,[]) endTag(DIV) endTag(BODY) effectiveBodyTag([]) endDoc() startDoc() markManufacturedBody() startTag(BODY,[]) startTag(DIV,[]) endTag(DIV) endTag(BODY) effectiveBodyTag([]) endDoc()".split(" "))});it("skips over comments",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;
(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<div>\x3c!-- this is a comment --\x3e</div>");expect(a.log).toEqual("startDoc() markManufacturedBody() startTag(BODY,[]) startTag(DIV,[]) endTag(DIV) endTag(BODY) effectiveBodyTag([]) endDoc()".split(" "))});it("processes unknown or custom tags",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,'<a-tag><more-tags><custom foo="Hello">world.</more-tags></a-tag>');
expect(a.log).toEqual('startDoc() markManufacturedBody() startTag(BODY,[]) startTag(A-TAG,[]) startTag(MORE-TAGS,[]) startTag(CUSTOM,[foo,Hello]) pcdata("world.") endTag(CUSTOM) endTag(MORE-TAGS) endTag(A-TAG) endTag(BODY) effectiveBodyTag([]) endDoc()'.split(" "))});it("parses oddly formatted attributes",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,'<a href="foo.html""></a>');expect(a.log).toEqual('startDoc() markManufacturedBody() startTag(BODY,[]) startTag(A,[",,href,foo.html]) endTag(A) endTag(BODY) effectiveBodyTag([]) endDoc()'.split(" "))});
it("closes <p> tags with omitted </p> tags implicitly",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<p>I am not closed!<p>I am closed!</p>");expect(a.log).toEqual('startDoc();markManufacturedBody();startTag(BODY,[]);startTag(P,[]);pcdata("I am not closed!");endTag(P);startTag(P,[]);pcdata("I am closed!");endTag(P);endTag(BODY);effectiveBodyTag([]);endDoc()'.split(";"))});it("closes <dd> and <dt> with omitted </dd> and </dt> implicitly",
function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<dl><dd><dd><dt><dd></dl>");expect(a.log).toEqual("startDoc() markManufacturedBody() startTag(BODY,[]) startTag(DL,[]) startTag(DD,[]) endTag(DD) startTag(DD,[]) endTag(DD) startTag(DT,[]) endTag(DT) startTag(DD,[]) endTag(DD) endTag(DL) endTag(BODY) effectiveBodyTag([]) endDoc()".split(" "))});it("closes <li> tags with omitted </li> tags implicitly",function(){var a=
new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<ul><li><li></ul>");expect(a.log).toEqual("startDoc() markManufacturedBody() startTag(BODY,[]) startTag(UL,[]) startTag(LI,[]) endTag(LI) startTag(LI,[]) endTag(LI) endTag(UL) endTag(BODY) effectiveBodyTag([]) endDoc()".split(" "))});it("reports attributes on the effective body tag",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandler;(new module$exports$amp$htmlparser.HtmlParser).parse(a,
"<body foo=bar><body baz=bang><body foo=poo>");expect(a.log).toEqual(["startDoc()","startTag(BODY,[foo,bar])","endTag(BODY)","effectiveBodyTag([foo,bar,baz,bang,foo,poo])","endDoc()"])})});var module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation=function(){module$exports$amp$htmlparser$interface.HtmlSaxHandlerWithLocation.call(this);this.locator=null;this.log=[]};$jscomp.inherits(module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation,module$exports$amp$htmlparser$interface.HtmlSaxHandlerWithLocation);
module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation.prototype.setDocLocator=function(a){this.locator=a;this.log=[]};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation.prototype.startDoc=function(){this.log.push(":"+this.locator.getLine()+":"+this.locator.getCol()+": startDoc()")};
module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation.prototype.cdata=function(a){this.log.push(":"+this.locator.getLine()+":"+this.locator.getCol()+': cdata("'+a+'")')};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation.prototype.pcdata=function(a){this.log.push(":"+this.locator.getLine()+":"+this.locator.getCol()+': pcdata("'+a+'")')};
module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation.prototype.rcdata=function(a){this.log.push(":"+this.locator.getLine()+":"+this.locator.getCol()+': rcdata("'+a+'")')};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation.prototype.endDoc=function(){this.log.push(":"+this.locator.getLine()+":"+this.locator.getCol()+": endDoc()")};
module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation.prototype.startTag=function(a){a.dedupeAttrs();this.log.push(":"+this.locator.getLine()+":"+this.locator.getCol()+": startTag("+a.upperName()+","+this.attrsToString(a.attrs())+")")};module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation.prototype.endTag=function(a){this.log.push(":"+this.locator.getLine()+":"+this.locator.getCol()+": endTag("+a.upperName()+")")};
module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation.prototype.attrsToString=function(a){var b="[",c=!0;a=$jscomp.makeIterator(a);for(var d=a.next();!d.done;d=a.next())d=d.value,c?c=!1:b+=",",b+=d.name+","+d.value;return b+"]"};
describe("HtmlParser with location",function(){it("reports line and column",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<html>\n  <body>\n    <div style=foo>Oh hi!</div>\n  </body>\n</html>");expect(a.log).toEqual(':1:0: startDoc();:1:0: startTag(HTML,[]);:1:6: pcdata("\n  ");:2:2: startTag(BODY,[]);:2:8: pcdata("\n    ");:3:4: startTag(DIV,[style,foo]);:3:19: pcdata("Oh hi!");:3:25: endTag(DIV);:3:31: pcdata("\n  ");:4:9: pcdata("\n");:5:0: endTag(BODY);:5:0: endTag(HTML);:5:6: endDoc()'.split(";"))});
it("does not insert closing events as html5 standard would suggest",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<html>\n  <body>\n    <p>\n      <a-custom>\n        <div style=foo>Oh hi!</div>\n      </a-custom>\n    </p>\n  </body>\n</html>");expect(a.log).toEqual(':1:0: startDoc();:1:0: startTag(HTML,[]);:1:6: pcdata("\n  ");:2:2: startTag(BODY,[]);:2:8: pcdata("\n    ");:3:4: startTag(P,[]);:3:7: pcdata("\n      ");:4:6: startTag(A-CUSTOM,[]);:4:16: pcdata("\n        ");:5:8: startTag(DIV,[style,foo]);:5:23: pcdata("Oh hi!");:5:29: endTag(DIV);:5:35: pcdata("\n      ");:6:6: endTag(A-CUSTOM);:6:17: pcdata("\n    ");:7:4: endTag(P);:7:8: pcdata("\n  ");:8:9: pcdata("\n");:9:0: endTag(BODY);:9:0: endTag(HTML);:9:6: endDoc()'.split(";"))});
it("tracks line and column past complex cdata sections",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation;(new module$exports$amp$htmlparser.HtmlParser).parse(a,'<html>\n<body>\n<script type="application/json">\n{\n"vars": {\n"account": "UA-XXXX-Y"\n},\n"triggers": {\n"default pageview": {\n"on": "visible"\n}\n}\n}\n\x3c/script>\n<amp-analytics></amp-analytics>\n</body>\n</html>');expect(a.log).toEqual(':1:0: startDoc();:1:0: startTag(HTML,[]);:1:6: pcdata("\n");:2:0: startTag(BODY,[]);:2:6: pcdata("\n");:3:0: startTag(SCRIPT,[type,application/json]);:3:0: cdata("\n{\n"vars": {\n"account": "UA-XXXX-Y"\n},\n"triggers": {\n"default pageview": {\n"on": "visible"\n}\n}\n}\n");:14:0: endTag(SCRIPT);:14:9: pcdata("\n");:15:0: startTag(AMP-ANALYTICS,[]);:15:15: endTag(AMP-ANALYTICS);:15:31: pcdata("\n");:16:7: pcdata("\n");:17:0: endTag(BODY);:17:0: endTag(HTML);:17:6: endDoc()'.split(";"))});
it("Supports Turkish UTF8 \u0130 character in body",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation;(new module$exports$amp$htmlparser.HtmlParser).parse(a,'<!doctype html>\n<html amp lang="tr">\n<head>\n<meta charset="utf-8">\n<title></title>\n<script async src="https://cdn.ampproject.org/v0.js">\x3c/script>\n</head>\n<body>\u0130</body>\n</html>');expect(a.log).toEqual(':1:0: startDoc();:1:0: startTag(!DOCTYPE,[html,]);:1:15: pcdata("\n");:2:0: startTag(HTML,[amp,,lang,tr]);:2:20: pcdata("\n");:3:0: startTag(HEAD,[]);:3:6: pcdata("\n");:4:0: startTag(META,[charset,utf-8]);:4:0: endTag(META);:4:22: pcdata("\n");:5:0: startTag(TITLE,[]);:5:0: rcdata("");:5:7: endTag(TITLE);:5:15: pcdata("\n");:6:0: startTag(SCRIPT,[async,,src,https://cdn.ampproject.org/v0.js]);:6:0: cdata("");:6:53: endTag(SCRIPT);:6:62: pcdata("\n");:7:0: endTag(HEAD);:7:7: pcdata("\n");:8:0: startTag(BODY,[]);:8:6: pcdata("\u0130");:8:14: pcdata("\n");:9:0: endTag(BODY);:9:0: endTag(HTML);:9:6: endTag(!DOCTYPE);:9:6: endDoc()'.split(";"))});
it("Supports SVG with self-closed tags",function(){var a=new module$contents$amp$htmlparser$HtmlParserTest_LoggingHandlerWithLocation;(new module$exports$amp$htmlparser.HtmlParser).parse(a,"<html><body><svg><foo/></svg></body></html>");expect(a.log).toEqual(":1:0: startDoc();:1:0: startTag(HTML,[]);:1:6: startTag(BODY,[]);:1:12: startTag(SVG,[]);:1:17: startTag(FOO,[]);:1:23: endTag(FOO);:1:23: endTag(SVG);:1:36: endTag(BODY);:1:36: endTag(HTML);:1:42: endDoc()".split(";"))})});
