(function(){var f,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var k;
if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var ca={a:!0},n={};try{n.__proto__=ca;l=n.a;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=k;function da(a){return(a=Number(a))?0<a?1:-1:a};var ea=Object.prototype.hasOwnProperty;function fa(a,b){if(null==a)throw new TypeError("Cannot convert undefined or null to object");for(var c=Object(a),d=1;d<arguments.length;d++){var e=arguments[d];if(null!=e)for(var g in e)ea.call(e,g)&&(c[g]=e[g])}return c};function ha(a){return Object.keys(a).map(function(b){return a[b]})};(function(a){a.Math.sign||a.Object.defineProperty(a.Math,"sign",{enumerable:!1,configurable:!0,writable:!0,value:da})})(self);(function(a){a.Object.assign||a.Object.defineProperty(a.Object,"assign",{enumerable:!1,configurable:!0,writable:!0,value:fa})})(self);(function(a){a.Object.values||a.Object.defineProperty(a.Object,"values",{configurable:!0,writable:!0,value:ha})})(self);function t(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ia=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function u(a){var b=Object.create(null);if(!a)return b;for(var c;c=ia.exec(a);){var d=t(c[1],c[1]),e=c[2]?t(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var v="";
function w(a){var b=a||self;if(b.__AMP_MODE)b=b.__AMP_MODE;else{var c=u(b.location.originalHash||b.location.hash);var d=u(b.location.search);v||(v=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012007102309000");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(c.development)||b.AMP_DEV_MODE),examiner:"2"==c.development,esm:!1,geoOverride:c["amp-geo"],minified:!0,lite:void 0!=d.amp_lite,test:!1,log:c.log,version:"2007102309000",rtvVersion:v};b=b.__AMP_MODE=c}return b}
;var x=Object.prototype.toString;function ja(a){var b=!1,c=null,d=a;return function(a){for(var e=[],h=0;h<arguments.length;++h)e[h-0]=arguments[h];b||(c=d.apply(self,e),b=!0,d=null);return c}};var y=self.AMP_CONFIG||{},z=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function A(a){if(!self.document||!self.document.head||self.location&&z.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var ka={thirdParty:y.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:y.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof y.thirdPartyFrameRegex?new RegExp(y.thirdPartyFrameRegex):y.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:y.cdnUrl||A("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:z,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:y.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:y.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:y.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:y.geoApiUrl||A("amp-geo-api")};function la(){}function ma(a,b){return b.reduce(function(a,b){return a+"&s[]="+encodeURIComponent(String(B(b)))},"https://log.amp.dev/?v=012007102309000&id="+encodeURIComponent(a))}
function C(a,b,c){var d=this;c=void 0===c?"":c;this.win=a;this.N=b;this.o=this.win.console&&this.win.console.log&&"0"!=w().log?this.N(parseInt(w().log,10),w().development):0;this.C=c;this.B=null;this.M=ja(function(){a.fetch(ka.cdn+"/rtv/012007102309000/log-messages.simple.json").then(function(a){return a.json()},la).then(function(a){a&&(d.B=a)})})}
function D(a,b,c,d){if(0!=a.o){var e=a.win.console.log;"ERROR"==c?e=a.win.console.error||e:"INFO"==c?e=a.win.console.info||e:"WARN"==c&&(e=a.win.console.warn||e);c=Array.isArray(d[0])?E(a,d[0]):d;b="["+b+"]";"string"===typeof c[0]?c[0]=b+" "+c[0]:c.unshift(b);e.apply(a.win.console,c)}}f=C.prototype;f.isEnabled=function(){return 0!=this.o};f.fine=function(a,b){4<=this.o&&D(this,a,"FINE",Array.prototype.slice.call(arguments,1))};
f.info=function(a,b){3<=this.o&&D(this,a,"INFO",Array.prototype.slice.call(arguments,1))};f.warn=function(a,b){2<=this.o&&D(this,a,"WARN",Array.prototype.slice.call(arguments,1))};f.H=function(a,b){if(1<=this.o)D(this,a,"ERROR",Array.prototype.slice.call(arguments,1));else{var c=F.apply(null,Array.prototype.slice.call(arguments,1));G(this,c);return c}};f.error=function(a,b){var c=this.H.apply(this,arguments);c&&(c.name=a||c.name,self.__AMP_REPORT_ERROR(c))};
f.expectedError=function(a,b){var c=this.H.apply(this,arguments);c&&(c.expected=!0,self.__AMP_REPORT_ERROR(c))};f.createError=function(a){var b=F.apply(null,arguments);G(this,b);return b};f.createExpectedError=function(a){var b=F.apply(null,arguments);G(this,b);b.expected=!0;return b};
f.assert=function(a,b,c){var d;if(Array.isArray(b))return this.assert.apply(this,[a].concat(E(this,b)));if(!a){var e=(b||"Assertion failed").split("%s"),g=e.shift(),h=g,q=[],m=2;for(""!=g&&q.push(g);0<e.length;){var T=e.shift(),r=arguments[m++];r&&r.tagName&&(d=r);q.push(r);g=T.trim();""!=g&&q.push(g);h+=B(r)+T}m=Error(h);m.fromAssert=!0;m.associatedElement=d;m.messageArray=q;G(this,m);self.__AMP_REPORT_ERROR(m);throw m;}return a};
f.assertElement=function(a,b){H(this,a,a&&1==a.nodeType,"Element expected",b);return a};f.assertString=function(a,b){H(this,a,"string"==typeof a,"String expected",b);return a};f.assertNumber=function(a,b){H(this,a,"number"==typeof a,"Number expected",b);return a};f.assertArray=function(a,b){H(this,a,Array.isArray(a),"Array expected",b);return a};f.assertBoolean=function(a,b){H(this,a,!!a===a,"Boolean expected",b);return a};
f.assertEnumValue=function(a,b,c){a:{for(var d in a)if(a[d]===b){a=!0;break a}a=!1}if(a)return b;this.assert(!1,'Unknown %s value: "%s"',c||"enum",b)};function G(a,b){b=I(b);a.C?b.message?-1==b.message.indexOf(a.C)&&(b.message+=a.C):b.message=a.C:0<=b.message.indexOf("\u200b\u200b\u200b")&&(b.message=b.message.replace("\u200b\u200b\u200b",""))}function E(a,b){var c=b.shift();w(a.win).development&&a.M();return a.B&&c in a.B?[a.B[c]].concat(b):["More info at "+ma(c,b)]}
function H(a,b,c,d,e){Array.isArray(e)?a.assert(c,e.concat(b)):a.assert(c,(e||d)+": %s",b)}function B(a){return a&&1==a.nodeType?a.tagName.toLowerCase()+(a.id?"#"+a.id:""):a}function I(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}
function F(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=I(e):(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var J=self.__AMP_LOG,K=null;function na(){if(!K)throw Error("failed to call initLogConstructor");return new K(self,function(a,b){return b||1<=a?4:2},"\u200b\u200b\u200b")}
function L(){if(J.dev)return J.dev;if(!K)throw Error("failed to call initLogConstructor");return J.dev=new K(self,function(a){return 3<=a?4:2<=a?3:0})};function M(a){return a||{}};var N;function oa(a,b){var c=pa();a.addEventListener("message",function(a){try{return b(a)}catch(e){throw self.__AMP_REPORT_ERROR(e),e;}},c?void 0:!1)}function pa(){if(void 0!==N)return N;N=!1;try{var a={get capture(){N=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return N};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function qa(a,b){oa(a,b)};function O(){this.j=null}f=O.prototype;f.add=function(a){var b=this;this.j||(this.j=[]);this.j.push(a);return function(){b.remove(a)}};f.remove=function(a){this.j&&(a=this.j.indexOf(a),-1<a&&this.j.splice(a,1))};f.removeAll=function(){this.j&&(this.j.length=0)};f.fire=function(a){if(this.j)for(var b=this.j,c=0;c<b.length;c++)(0,b[c])(a)};f.getHandlerCount=function(){return this.j?this.j.length:0};function P(a,b){this.h=a;this.P=w().rtvVersion||null;this.m=b||null;this.F=null;this.O=1;this.w=Object.create(null);ra(this)}f=P.prototype;f.getData=function(a,b,c){var d=a+"-result",e=this.O++,g=this.registerCallback(d,function(a){a.messageId===e&&(g(),c(a.content))}),h={};h.payload=b;h.messageId=e;this.sendMessage(a,h)};f.makeRequest=function(a,b,c){b=this.registerCallback(b,c);this.sendMessage(a);return b};
f.requestOnce=function(a,b,c){var d=this.registerCallback(b,function(a){d();c(a)});this.sendMessage(a);return d};f.registerCallback=function(a,b){a in this.w||(this.w[a]=new O);return this.w[a].add(b)};
f.sendMessage=function(a,b){var c=this.F,d=b,e=this.P;d=void 0===d?{}:d;d.type=a;d.sentinel=c;a="amp-"+((void 0===e?null:e)||"")+JSON.stringify(d);if(this.m)c=this.m,1==c.postMessage.length?Q(c,a):c.postMessage(a,"*");else for(var g=0,h=this.h;10>g&&h!=this.h.top;g++)c=h=h.parent,e=a,1==c.postMessage.length?Q(c,e):c.postMessage(e,"*"),g++};function Q(a,b){a.postMessage(b,M({targetOrigin:"*",includeUserActivation:!0}))}
function ra(a){qa(a.h,function(b){if(!a.m||b.source==a.m){var c=b.data;if("string"==typeof c&&0==c.indexOf("amp-")&&-1!=c.indexOf("{")){var d=c.indexOf("{");try{var e=JSON.parse(c.substr(d))}catch(g){L().error("MESSAGING","Failed to parse message: "+c,g),e=null}}else e=null;e&&e.sentinel==a.F&&(e.origin=b.origin,a.m||(a.m=b.source),b=e.type,b in a.w&&a.w[b].fire(e))}})}f.setSentinel=function(a){this.F=a};function R(){this.K=100;this.D=this.G=0;this.A=Object.create(null)}R.prototype.has=function(a){return!!this.A[a]};R.prototype.get=function(a){var b=this.A[a];if(b)return b.access=++this.D,b.payload};R.prototype.put=function(a,b){this.has(a)||this.G++;this.A[a]={payload:b,access:this.D};if(!(this.G<=this.K)){L().warn("lru-cache","Trimming LRU cache");a=this.A;b=this.D+1;var c;for(c in a){var d=a[c].access;if(d<b){b=d;var e=c}}void 0!==e&&(delete a[e],this.G--)}};M({c:!0,v:!0,a:!0,ad:!0,action:!0});var S,U;function V(a){this.I();this.h=a;this.J=this.h.name||null;this.tagName=this.startTime=this.sourceUrl=this.sentinel=this.referrer=this.pageViewId=this.mode=this.location=this.initialIntersection=this.initialLayoutRect=this.initialConsentValue=this.initialConsentState=this.hidden=this.domFingerprint=this.data=this.consentSharedData=this.container=this.clientId=this.canonicalUrl=this.canary=this.L=null;"[object Object]"===x.call(this.h.sf_)&&this.h.sf_.cfg?W(this,this.h.sf_.cfg):this.h.AMP_CONTEXT_DATA?
"string"==typeof this.h.AMP_CONTEXT_DATA?this.sentinel=this.h.AMP_CONTEXT_DATA:"[object Object]"===x.call(this.h.AMP_CONTEXT_DATA)&&W(this,this.h.AMP_CONTEXT_DATA):W(this,this.h.name);var b=this.sentinel.match(/((\d+)-\d+)/);b=Number(b[2]);for(var c=[],d=this.h;d&&d!=d.parent;d=d.parent)c.push(d.parent);this.l=new P(a,c[c.length-1-b]);this.l.setSentinel(this.sentinel);sa(this)}f=V.prototype;f.I=function(){};
function sa(a){a.l.makeRequest("send-embed-state","embed-state",function(b){a.hidden=b.pageHidden;b=a.h.document.createEvent("Event");b.data={hidden:a.hidden};b.initEvent("amp:visibilitychange",!0,!0);a.h.dispatchEvent(b)})}f.onPageVisibilityChange=function(a){return this.l.registerCallback("embed-state",function(b){a({hidden:b.pageHidden})})};f.observeIntersection=function(a){return this.l.makeRequest("send-intersections","intersection",function(b){a(b.changes)})};
f.getHtml=function(a,b,c){this.l.getData("get-html",M({selector:a,attributes:b}),c)};f.getConsentState=function(a){this.l.getData("get-consent-state",null,a)};f.requestResize=function(a,b,c){this.l.sendMessage("embed-size",M({width:a,height:b,hasOverflow:c}))};f.onResizeSuccess=function(a){this.l.registerCallback("embed-size-changed",function(b){a(b.requestedHeight,b.requestedWidth)})};f.onResizeDenied=function(a){this.l.registerCallback("embed-size-denied",function(b){a(b.requestedHeight,b.requestedWidth)})};
f.addContextToIframe=function(a){a.name=this.J};f.noContentAvailable=function(){this.l.sendMessage("no-content")};
function W(a,b){if("string"===typeof b)try{var c=JSON.parse(b)}catch(q){c=null}else c=b;var d=c;b=d._context||d.attributes._context;a.data=d.attributes||d;"_context"in a.data&&delete a.data._context;a.canary=b.canary;a.canonicalUrl=b.canonicalUrl;a.clientId=b.clientId;a.consentSharedData=b.consentSharedData;a.container=b.container;a.domFingerprint=b.domFingerprint;a.hidden=b.hidden;a.initialConsentState=b.initialConsentState;a.initialConsentValue=b.initialConsentValue;a.initialLayoutRect=b.initialLayoutRect;
a.initialIntersection=b.initialIntersection;c=b.location.href;S||(S=self.document.createElement("a"),U=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new R));var e=U,g=S;if(e&&e.has(c))c=e.get(c);else{g.href=c;g.protocol||(g.href=g.href);var h={href:g.href,protocol:g.protocol,host:g.host,hostname:g.hostname,port:"0"==g.port?"":g.port,pathname:g.pathname,search:g.search,hash:g.hash,origin:null};"/"!==h.pathname[0]&&(h.pathname="/"+h.pathname);if("http:"==h.protocol&&80==h.port||"https:"==h.protocol&&
443==h.port)h.port="",h.host=h.hostname;h.origin=g.origin&&"null"!=g.origin?g.origin:"data:"!=h.protocol&&h.host?h.protocol+"//"+h.host:h.href;e&&e.put(c,h);c=h}a.location=c;a.mode=b.mode;a.pageViewId=b.pageViewId;a.referrer=b.referrer;a.sentinel=b.sentinel;a.sourceUrl=b.sourceUrl;a.startTime=b.startTime;a.tagName=b.tagName;a.L=d.type||null}f.report3pError=function(a){a.message&&this.l.sendMessage("user-error-in-iframe",M({message:a.message}))};function X(){V.apply(this,arguments)}X.prototype=aa(V.prototype);
X.prototype.constructor=X;if(p)p(X,V);else for(var Y in V)if("prototype"!=Y)if(Object.defineProperties){var Z=Object.getOwnPropertyDescriptor(V,Y);Z&&Object.defineProperty(X,Y,Z)}else X[Y]=V[Y];X.R=V.prototype;X.prototype.I=function(){};(function(){K=C;L();J.user||(J.user=na())})();(function(a){self.__AMP_REPORT_ERROR=a})(function(){});try{var windowContextCreated=new Event("amp-windowContextCreated");window.context=new X(window);window.dispatchEvent(windowContextCreated)}catch(a){};})();

//# sourceMappingURL=ampcontext-v0.js.map
